"""
Matchup Intelligence Report — the canonical, scannable output of the unified MLB Model.

A research/trading TERMINAL, not a written report. It follows the Sharp Money Tracker / Chase
Analytics design system (violet, Roboto Condensed + tabular nums, percentile color chips
c-elite..c-poor, premium tables, comparison bars, inline SVG charts). Presentation order:
raw number -> visual context -> comparative meaning -> modeled implication -> (optional) explanation.

Powered by the unified expected-runs, paired-pricing, risk, MLBMA context, and warehouse
modules. Every modeled driver is generated by the probability calculation itself; descriptive
context is labeled separately.
"""
from __future__ import annotations

import argparse
import html
import math
from datetime import datetime, timezone

from mlbmodel import settings
from mlbmodel.baseball.model import (
    fair_price,
    market_probability,
    model_probabilities,
    normal_cdf,
    offense_factor,
    pitch_factor,
)
from mlbmodel.baseball.repository import DataRepository
from mlbmodel.baseball.risk import risk_signals
from mlbmodel.baseball.simulation import simulate_game
from mlbmodel.market.quotes import OddsBoard, load_board
from mlbmodel.market.value import assess_value
from mlbmodel.quant.promotion_gate import promotion_verdict
from mlbmodel.storage.supabase import SupabaseReader


def _live_odds(fetch=True) -> OddsBoard:
    return load_board(fetch=fetch)


# ── visual identity: official MLB team logos + pitcher headshots (CDN) ───────
_MLB_ID = {"ARI": 109, "ATL": 144, "BAL": 110, "BOS": 111, "CHC": 112, "CHW": 145,
           "CIN": 113, "CLE": 114, "COL": 115, "DET": 116, "HOU": 117, "KCR": 118,
           "LAA": 108, "LAD": 119, "MIA": 146, "MIL": 158, "MIN": 142, "NYM": 121,
           "NYY": 147, "ATH": 133, "PHI": 143, "PIT": 134, "SDP": 135, "SFG": 137,
           "SEA": 136, "STL": 138, "TBR": 139, "TEX": 140, "TOR": 141, "WSN": 120}


def _logo(abbr, cls="tlogo"):
    a = str(abbr).upper().strip()
    i = _MLB_ID.get(a)
    if not i:
        return f'<span class="tlf {cls}">{html.escape(a)}</span>'
    return (f'<img class="{cls}" src="https://www.mlbstatic.com/team-logos/{i}.svg" '
            f'alt="" aria-hidden=true loading="lazy" '
            f'onerror="this.outerHTML=&quot;<span class=\'tlf {cls}\'>{html.escape(a)}</span>&quot;">')


def _headshot(pid):
    if not pid:
        return '<span class="phead phead-na"></span>'
    return (f'<img class=phead loading="lazy" alt="" '
            f'src="https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:67:current.png/'
            f'w_120,q_auto:best/v1/people/{int(pid)}/headshot/67/current" '
            f'onerror="this.classList.add(&quot;phead-na&quot;)">')


# ── stat helpers (raw -> percentile -> semantic chip) ────────────────────────
def _cdf(z: float) -> float:
    return 0.5 * (1 + math.erf(z / math.sqrt(2)))


def _emp_pctile(series, value: float, lower_better: bool) -> float | None:
    """Empirical percentile of `value` within `series` (a pandas Series). 0..100."""
    try:
        import pandas as pd
        s = pd.to_numeric(series, errors="coerce").dropna()
        if s.empty or value is None:
            return None
        p = float((s < value).mean()) * 100
        return round(100 - p if lower_better else p, 0)
    except Exception:
        return None


def _chip(pct: float | None) -> tuple[str, str]:
    """Percentile -> (css class, label) using the Sharp Money Tracker scale."""
    if pct is None:
        return "c-na", "—"
    if pct >= 90:
        return "c-elite", "elite"
    if pct >= 70:
        return "c-good", "strong"
    if pct >= 40:
        return "c-mid", "avg"
    if pct >= 20:
        return "c-weak", "weak"
    return "c-poor", "poor"


def _f(v, nd=2):
    return f"{v:.{nd}f}" if isinstance(v, (int, float)) else "—"


_DEF = {
    "FIP": "Fielding-Independent Pitching — ERA from what a pitcher controls (K/BB/HR). Lower is better.",
    "K%": "Strikeout rate. Higher = more swings-and-misses, fewer balls in play.",
    "HR/9": "Home runs allowed per 9 innings. Lower is better.",
    "OSI": "Offense Strength Index (50 = league average). Higher = stronger lineup.",
    "ABQ": "At-Bat Quality. Higher indicates more consistently productive plate appearances.",
    "RCV": "Run Creation Value. Higher indicates stronger run-producing quality.",
    "PALS": "Pressure-Adjusted Lineup Strength. Higher indicates a stronger projected lineup.",
    "projOSI": "Projected Offense Strength Index for the expected lineup.",
    "wOBA": "Weighted On-Base Average — overall offensive value. Higher is better (~.320 avg).",
    "OBR": "Baserunning index (50 = average). Higher = better baserunning.",
    "Bullpen": "Relief run-prevention. Lower factor / ERA is better.",
    "Park": "Park run environment (1.00 = neutral; >1 boosts scoring).",
}


def _cat_def(cat):
    for k, v in _DEF.items():
        if k in cat:
            return v
    return ""


# ── factor decomposition (drivers) ───────────────────────────────────────────
def _factors(probs):
    out = [
        {
            "name": factor.name,
            "pct": round((factor.multiplier - 1) * 100, 1),
            "runs": round(factor.run_delta, 2),
            "side": factor.side,
            "market": factor.markets,
            "conf": factor.confidence,
            "source": factor.source,
        }
        for factor in probs.factors
    ]
    return sorted(out, key=lambda value: -abs(value["runs"]))


# ── advantage matrix (team vs team, with empirical percentiles + rank) ────────
def _rank(pct, n):
    """Rank (1 = best) implied by a percentile within n peers."""
    if pct is None or not n:
        return None
    return max(1, round((100 - pct) / 100 * n) + 1)


def _col(df, name):
    return df[name] if df is not None and name in df.columns else None


def _tv(idx, team, col):
    import pandas as pd
    r = idx.get(str(team).upper().strip())
    if r is None or col not in r:
        return None
    v = pd.to_numeric(r[col], errors="coerce")
    return None if pd.isna(v) else float(v)


def _advantage(gd, anchors, repo):
    import pandas as pd
    sp = repo.load("sp_profiles.csv")
    tp = repo.load("team_profiles.csv")
    fip_s, k_s, hr_s = _col(sp, "FIP"), _col(sp, "K_pct"), _col(sp, "HR9")
    osi_s = _col(tp, "osi")
    abq_s = _col(tp, "abq")
    rcv_s = _col(tp, "rcv")
    pals_s = _col(tp, "pals")
    proj_s = _col(tp, "proj_osi")
    osi_l7_s = _col(tp, "osi_l7")
    idx = {str(r["team"]).upper().strip(): r for _, r in tp.iterrows()} if tp is not None and "team" in tp.columns else {}
    # pooled series for split-based baselines
    plat_s = pd.concat([s for s in (_col(tp, "osi_vs_lhp"), _col(tp, "osi_vs_rhp")) if s is not None]) if tp is not None else None
    woba_s = pd.concat([s for s in (_col(tp, "home_woba"), _col(tp, "away_woba")) if s is not None]) if tp is not None else None
    obr_s = _col(tp, "obr")
    bhl_s = _col(tp, "bullpen_high_lev_era")
    a_plat_col = "osi_vs_lhp" if gd.home_hand == "L" else "osi_vs_rhp"   # away faces home SP hand
    h_plat_col = "osi_vs_lhp" if gd.away_hand == "L" else "osi_vs_rhp"   # home faces away SP hand

    def _mean(series, default):
        try:
            import pandas as pd
            s = pd.to_numeric(series, errors="coerce").dropna()
            return (round(float(s.mean()), 2), int(s.shape[0])) if len(s) else (default, 0)
        except Exception:
            return (default, 0)

    rows = []

    def row(cat, a_val, h_val, series, lower_better, base_default, impact, unit="", role="context"):
        ap = _emp_pctile(series, a_val, lower_better) if series is not None else None
        hp = _emp_pctile(series, h_val, lower_better) if series is not None else None
        base, n = _mean(series, base_default) if series is not None else (base_default, None)
        edge = "—"
        if ap is not None and hp is not None:
            edge = gd.away if ap > hp else (gd.home if hp > ap else "even")
        # stat-presentation standard: raw + baseline + delta + percentile + sample
        ad = (round(a_val - base, 2) if isinstance(a_val, (int, float)) and base is not None else None)
        hd = (round(h_val - base, 2) if isinstance(h_val, (int, float)) and base is not None else None)
        rows.append({"cat": cat, "a_val": a_val, "h_val": h_val, "a_pct": ap, "h_pct": hp,
                     "base": base, "a_d": ad, "h_d": hd, "n": n, "edge": edge,
                     "a_rank": _rank(ap, n), "h_rank": _rank(hp, n),
                     "impact": impact, "unit": unit, "lower_better": lower_better,
                     "role": role})

    # pitching
    row("Starting pitching (FIP)", gd.away_fip, gd.home_fip, fip_s, True, settings.LEAGUE_FIP,
        f"{(pitch_factor(gd.home_fip, gd.home_pen_factor) - pitch_factor(gd.away_fip, gd.away_pen_factor)) * anchors['league_runs']:+.2f} R",
        role="modeled")
    row("SP strikeout (K%)", gd.away_k, gd.home_k, k_s, False, 22.0, "K props · Total", "%")
    row("SP home-run risk (HR/9)", gd.away_hr9, gd.home_hr9, hr_s, True, 1.25, "Total · TT")
    # offense
    row("Offense (OSI)", gd.away_osi, gd.home_osi, osi_s, False, 50.0,
        f"{(offense_factor(gd.away_osi) - offense_factor(gd.home_osi)) * anchors['league_runs']:+.2f} R",
        role="modeled")
    row("At-bat quality (ABQ)", gd.away_context.abq, gd.home_context.abq, abq_s, False,
        50.0, "Research context")
    row("Run creation value (RCV)", gd.away_context.rcv, gd.home_context.rcv, rcv_s, False,
        50.0, "Research context")
    row("Pressure-adjusted lineup (PALS)", gd.away_context.pals, gd.home_context.pals,
        pals_s, False, 50.0, "Research context")
    row("Projected offense (projOSI)", gd.away_context.proj_osi, gd.home_context.proj_osi,
        proj_s, False, 50.0, "Research context")
    row("Recent offense (OSI L7)", gd.away_context.osi_l7, gd.home_context.osi_l7,
        osi_l7_s, False, 50.0, "Research context")
    row(f"Platoon (OSI vs {gd.home_hand}HP/{gd.away_hand}HP)", _tv(idx, gd.away, a_plat_col), _tv(idx, gd.home, h_plat_col),
        plat_s, False, 50.0, "Total · ML")
    row("Lineup quality (wOBA)", _tv(idx, gd.away, "away_woba"), _tv(idx, gd.home, "home_woba"), woba_s, False, 0.320, "Total · ML")
    row("Baserunning (OBR)", _tv(idx, gd.away, "obr"), _tv(idx, gd.home, "obr"), obr_s, False, 50.0, "ML · close games")
    # relief + environment
    row("Bullpen (factor)", gd.away_pen_factor, gd.home_pen_factor, None, True, 1.00,
        "Late ML · Total", role="modeled")
    row("Bullpen high-leverage (ERA)", _tv(idx, gd.away, "bullpen_high_lev_era"), _tv(idx, gd.home, "bullpen_high_lev_era"),
        bhl_s, True, 4.00, "Late ML · live")
    row("Park run env", gd.park_factor, gd.park_factor, None, False, 1.00,
        "Total · TT", role="modeled")
    return rows


def _market_row(market, side, line, ou, gd, probs, anchors, quote, promotion):
    probability, description = market_probability(market, side, line, gd, probs, anchors, ou)
    probability = max(0.02, min(0.98, probability))
    assessment = assess_value(
        probability,
        quote.best_odds if quote else None,
        quote.vigfree_probability if quote else None,
        promotion_status=promotion,
    )
    tone = {
        "BET": "pos",
        "MONITOR": "warnc",
        "REVIEW": "warnc",
        "AVOID": "neg",
        "NO EDGE": "mut",
    }[assessment.action]
    return {
        "label": description,
        "model": round(probability * 100, 1),
        "fair": assessment.fair_odds,
        "mkt": quote.best_odds if quote else None,
        "book": quote.best_book if quote else None,
        "impl": (
            round(quote.vigfree_probability * 100, 1)
            if quote else None
        ),
        "edge": (
            round(assessment.edge * 100, 1)
            if assessment.edge is not None else None
        ),
        "ev": assessment.ev_per_unit,
        "max": assessment.maximum_odds,
        "state": assessment.action,
        "tone": tone,
        "reason": assessment.reason,
        "books": quote.book_count if quote else 0,
        "market_time": quote.fetched_at if quote else None,
    }


def _norm(s):
    import re
    t = " ".join(reversed(str(s).lower().split(","))) if "," in str(s) else str(s).lower()
    return " ".join(sorted(re.sub(r"[^a-z ]", "", t).split()))


def _numf(v):
    import pandas as pd
    x = pd.to_numeric(v, errors="coerce")
    return None if pd.isna(x) else float(x)


def _extras(away, home, gd, probs, anchors, repo):
    """Start time, lineup status, SP arsenals, scenario sweep, F5 — from real pipeline data."""
    out = {"start": None, "lineup": "lineups TBD · probables confirmed",
           "arsenal_a": [], "arsenal_h": [], "scenario": [], "f5": None}
    m = repo.load("today_matchups.csv")
    if m is not None and "Away" in m.columns:
        m["Away"] = m["Away"].astype(str).str.upper().str.strip()
        m["Home"] = m["Home"].astype(str).str.upper().str.strip()
        r = m[(m["Away"] == away) & (m["Home"] == home)]
        if not r.empty:
            out["start"] = str(r.iloc[0].get("Time", "") or "")
    ln = repo.load("today_lineups.csv")
    if ln is not None and not ln.empty:
        out["lineup"] = "lineups posted"
    pm = repo.load("pitch_mix_pitcher.csv")

    def arsenal(name):
        if pm is None or "full_name" not in pm.columns:
            return []
        key = _norm(name)
        sub = pm[pm["full_name"].astype(str).map(_norm) == key]
        rows = [{"pitch": str(x.get("pitch_type", "")), "pct": _numf(x.get("pitch_pct")),
                 "whiff": _numf(x.get("whiff_rate"))} for _, x in sub.iterrows()]
        return sorted([z for z in rows if z["pct"]], key=lambda z: -z["pct"])[:6]
    out["arsenal_a"], out["arsenal_h"] = arsenal(gd.away_sp), arsenal(gd.home_sp)
    spp = repo.load("sp_profiles.csv")

    def spid(name):
        if spp is None or "pitcher_name" not in spp.columns or "pitcher_id" not in spp.columns:
            return None
        m = spp[spp["pitcher_name"].astype(str).map(_norm) == _norm(name)]
        if not m.empty:
            v = _numf(m.iloc[0]["pitcher_id"])
            return int(v) if v else None
        return None
    out["a_id"], out["h_id"] = spid(gd.away_sp), spid(gd.home_sp)
    for d in (-1.5, -1, -0.5, 0, 0.5, 1, 1.5):
        line = round((probs.exp_total + d) * 2) / 2
        po = 1 - normal_cdf((line - probs.exp_total) / anchors["total_sd"])
        out["scenario"].append((line, round(po * 100, 1)))
    f5, sdf = probs.exp_total * 0.54, anchors["total_sd"] * 0.74
    line = round(f5 * 2) / 2
    po = max(0.02, min(0.98, 1 - normal_cdf((line - f5) / sdf)))
    out["f5"] = {
        "exp": round(f5, 1),
        "line": line,
        "over": round(po * 100, 1),
        "fair": fair_price(po),
    }
    return out


def _promotion(reader):
    result = reader.get(
        "prediction_market_snapshots?market_type=eq.ml&settled=eq.true"
        "&won=not.is.null&open_prob=not.is.null"
        "&select=game_pk,snapshot_time,open_prob,delta,won,"
        "implied_probability,volume,entry_prob,signal_time"
    )
    if result.error:
        return {"verdict": "HOLD/ABSTAIN", "reasons": [result.error]}
    return promotion_verdict(result.rows)


def build_report(
    away,
    home,
    *,
    fetch=True,
    data_dir=None,
    board=None,
    reader=None,
    gate=None,
    pitcher_rows=None,
):
    repo = DataRepository(data_dir)
    anchors = repo.anchors()
    gd = repo.load_game(away, home)
    probs = model_probabilities(gd, anchors)
    simulation = simulate_game(
        probs,
        team_runs_sd=anchors["team_sd"],
        seed=gd.game_pk,
    )
    board = board or _live_odds(fetch=fetch)
    reader = reader or SupabaseReader()
    gate = gate or _promotion(reader)
    promotion = "PROMOTE" if gate.get("verdict") == "PROMOTE" else "HOLD/ABSTAIN"
    posted_total = board.modal_total(away, home)
    tline = posted_total if posted_total is not None else round(probs.exp_total * 2) / 2
    markets = [
        _market_row("ml", gd.home, None, None, gd, probs, anchors,
                    board.quote(away, home, "ml", gd.home), promotion),
        _market_row("ml", gd.away, None, None, gd, probs, anchors,
                    board.quote(away, home, "ml", gd.away), promotion),
        _market_row("total", "over", tline, None, gd, probs, anchors,
                    board.quote(away, home, "total", "over", tline), promotion),
        _market_row("total", "under", tline, None, gd, probs, anchors,
                    board.quote(away, home, "total", "under", tline), promotion),
    ]
    runline_team = gd.home if probs.exp_margin > 0 else gd.away
    runline = -1.5
    markets.append(
        _market_row(
            "runline", runline_team, runline, None, gd, probs, anchors,
            board.quote(away, home, "runline", runline_team, runline), promotion,
        )
    )
    ex = _extras(away, home, gd, probs, anchors, repo)
    f5 = ex["f5"]
    markets.append({"label": f"F5 Over {f5['line']} (≈)", "model": f5["over"], "fair": f5["fair"],
                    "mkt": None, "impl": None, "edge": None, "ev": None, "max": f5["fair"],
                    "state": "NO EDGE", "tone": "mut", "reason": "No F5 market price",
                    "book": None, "books": 0, "market_time": None})
    conf = probs.confidence
    freshness = repo.freshness_hours("today_matchups.csv")
    return {"away": away, "home": home, "gd": gd, "probs": probs, "anchors": anchors,
            "posted_total": posted_total, "extras": ex, "movement": None, "confidence": conf,
            "markets": markets, "factors": _factors(probs),
            "advantage": _advantage(gd, anchors, repo), "simulation": simulation,
            "pitchers": pitcher_rows or [],
            "risks": risk_signals(gd), "sharp": _sharp_for(gd.game_pk, reader),
            "game_pk": gd.game_pk, "promotion": gate, "freshness_hours": freshness,
            "model_version": settings.MODEL_VERSION, "metric_version": settings.METRIC_VERSION,
            "generated": datetime.now(timezone.utc).isoformat(timespec="seconds")}


def _sharp_for(gpk, reader):
    result = reader.get(
        "sharp_signals"
        f"?game_pk=eq.{gpk}&select=market_type,selection,divergence,steam_flag,"
        "sharp_novig_prob,soft_novig_prob,snapshot_time"
    )
    return result.rows


# ── inline SVG charts (every chart answers a decision question) ───────────────
def _svg_winprob(ph, pa, home, away):
    hw = round(ph * 100)
    return (f'<svg viewBox="0 0 300 26" width="100%" height="26" preserveAspectRatio="none">'
            f'<rect x="0" y="6" width="{hw*3}" height="14" rx="4" fill="#2dd4bf"/>'
            f'<rect x="{hw*3}" y="6" width="{(100-hw)*3}" height="14" rx="4" fill="#9A6BFF"/></svg>'
            f'<div class="cap"><span class="pos">{home} {hw}%</span>'
            f'<span class="side">{away} {100-hw}%</span></div>')


def _svg_rundist(exp_a, exp_h, sd, away, home):
    """Two expected-run bell curves (away violet, home teal) over 0..12 runs."""
    def path(mu, color):
        pts = []
        for i in range(0, 121):
            x = i / 10
            y = math.exp(-((x - mu) ** 2) / (2 * sd ** 2))
            pts.append(f"{i*2.4:.1f},{70 - y*60:.1f}")
        return f'<polyline points="{" ".join(pts)}" fill="none" stroke="{color}" stroke-width="2"/>'
    grid = "".join(f'<line x1="{r*24}" y1="0" x2="{r*24}" y2="70" stroke="rgba(148,163,184,.10)"/>'
                   f'<text x="{r*24}" y="82" fill="#707687" font-size="9">{r}</text>' for r in range(0, 13, 2))
    return (f'<svg viewBox="0 0 290 88" width="100%" height="92">{grid}'
            f'{path(exp_a, "#9A6BFF")}{path(exp_h, "#2dd4bf")}</svg>'
            f'<div class="cap"><span class="side">{away} μ{exp_a:.1f}</span>'
            f'<span class="pos">{home} μ{exp_h:.1f}</span></div>')


def _bar(pct, tone):
    w = max(2, min(100, abs(pct) * 4))
    return f'<span class="dbar"><i style="width:{w}%;background:var(--{tone})"></i></span>'


def _svg_mktmodel(markets):
    """Model% vs market-implied% per market — the discrepancy at a glance."""
    rows = [m for m in markets if m["impl"] is not None][:4]
    if not rows:
        return '<div class=mut style="font-size:12px">No market prices to compare.</div>'
    out = ""
    for m in rows:
        edge = m["edge"] or 0
        tone = "pos" if edge > 0 else ("neg" if edge < 0 else "mut")
        out += (f'<div class=mm><span class=mml>{html.escape(m["label"])}</span>'
                f'<span class=mmbar><i class=mod style="width:{m["model"]:.0f}%"></i>'
                f'<i class=imp style="left:{m["impl"]:.0f}%"></i></span>'
                f'<span class="mmv {tone}">{edge:+.1f}pt</span></div>')
    return f'<div class=mmwrap>{out}<div class=cap><span class=side>model bar</span><span class=mut>● market</span></div></div>'


def _svg_arsenal(ars, label):
    if not ars:
        return f'<div class=mut style="font-size:11.5px">{label}: no pitch-mix data</div>'
    bars = "".join(
        f'<div class=arl><span class=apt>{html.escape(p["pitch"])}</span>'
        f'<span class=abar><i style="width:{min(100,p["pct"]):.0f}%"></i></span>'
        f'<span class=apv>{p["pct"]:.0f}%</span><span class=aw>whf {(p["whiff"] or 0):.0f}</span></div>'
        for p in ars)
    return f'<div class=arshd>{label}</div><div class=ars>{bars}</div>'


def _svg_scenario(scenario, mkt):
    if not scenario:
        return ""
    lines = [s[0] for s in scenario]
    lo, hi = min(lines), max(lines)
    pts = []
    for ln, ov in scenario:
        x = (ln - lo) / (hi - lo) * 260 + 10 if hi > lo else 135
        pts.append(f"{x:.0f},{70 - ov/100*60:.0f}")
    mk = ""
    if mkt is not None and lo <= mkt <= hi:
        x = (mkt - lo) / (hi - lo) * 260 + 10
        mk = f'<line x1="{x:.0f}" y1="2" x2="{x:.0f}" y2="72" stroke="#E8C24A" stroke-dasharray="3"/><text x="{x:.0f}" y="84" fill="#E8C24A" font-size="9" text-anchor="middle">mkt {mkt}</text>'
    labs = "".join(f'<text x="{(s[0]-lo)/(hi-lo)*260+10 if hi>lo else 135:.0f}" y="84" fill="#707687" font-size="8" text-anchor="middle">{s[0]:g}</text>' for s in scenario)
    return (f'<svg viewBox="0 0 290 90" width="100%" height="92">'
            f'<polyline points="{" ".join(pts)}" fill="none" stroke="#9A6BFF" stroke-width="2"/>{mk}{labs}</svg>'
            f'<div class=cap><span class=side>fair Over% vs total line</span></div>')


def _svg_movement(mv):
    if not mv or mv.get("snapshots", 0) < 2:
        return '<div class=mut style="font-size:11.5px">Line movement: single snapshot — re-fetch over time to build a timeline.</div>'
    o, c = mv.get("open"), mv.get("current")
    d = mv.get("delta", 0)
    tone = "pos" if d and d > 0 else "neg"
    return (f'<div class=mvrow><span class=mut>open</span><b>{o:+d}</b>'
            f'<span class=mvarrow>→</span><b>{c:+d}</b>'
            f'<span class="{tone}">Δ{d:+d} · {mv["snapshots"]} snaps</span></div>')


# ── render (Chase Analytics / Sharp Money Tracker design contract) ────────────
_CSS = """
@import url('https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@700;800&family=DM+Sans:wght@400;500;600;700;800&display=swap');
:root{color-scheme:dark;--bg:#08090F;--card:#12141D;--card-2:#181B26;--raised:#20232F;--border:#262A38;--border-2:#363B4D;
--ink:#F8F9FC;--ink2:#BCC0CC;--muted:#9196A6;--muted-2:#707687;--v-light:#C4B0FF;--accent:#9A6BFF;--v-deep:#5B2BE0;
--v-grad:linear-gradient(135deg,#9A6BFF,#5B2BE0);--green:#3CCB7F;--red:#F2545B;--gold:#E8C24A;--teal:#2DD4BF;--side:#C4B0FF;
--display:"Roboto Condensed",system-ui,sans-serif;--sans:"DM Sans",system-ui,sans-serif}
*{box-sizing:border-box}body{margin:0;color:var(--ink);font-family:var(--sans);font-size:15px;
background:radial-gradient(ellipse 90% 60% at 78% -8%,rgba(124,77,255,.14),transparent 58%),var(--bg);background-attachment:fixed}
.wrap{max-width:1180px;margin:0 auto;padding:22px 20px 70px;display:flex;flex-direction:column;gap:18px}
.num,td,th,.chip,.mval{font-variant-numeric:tabular-nums}.pos{color:var(--green)}.neg{color:var(--red)}.warnc{color:var(--gold)}.side{color:var(--side)}.mut{color:var(--muted)}
.c-elite{color:#4ADE80}.c-good{color:#7BDC5A}.c-mid{color:#FBBF24}.c-weak{color:#FB923C}.c-poor{color:#F87171}.c-na{color:var(--muted)}
/* header */
.hd{display:flex;justify-content:space-between;align-items:flex-end;gap:14px;border-bottom:1px solid var(--border);padding-bottom:14px;flex-wrap:wrap}
.hd h1{font-family:var(--display);font-weight:800;font-size:34px;letter-spacing:-.02em;margin:0;line-height:1}
.hd .sp{color:var(--ink2);font-size:13px;margin-top:6px}.hd .sp b{color:var(--ink)}
.hd .meta{color:var(--muted-2);font-size:11px;text-align:right;line-height:1.5}.fresh{color:var(--green);font-weight:700}
/* logos + headshots (Chase Analytics blueprint) */
.tlogo{height:26px;width:26px;object-fit:contain;vertical-align:middle;filter:drop-shadow(0 3px 5px rgba(0,0,0,.5))}
.tlogo.lg{height:40px;width:40px}.tlogo.sm{height:18px;width:18px}
.tlf{display:inline-flex;align-items:center;justify-content:center;height:26px;width:26px;border-radius:50%;
background:var(--raised);border:1px solid var(--border-2);color:var(--ink2);font:800 9px/1 var(--display);vertical-align:middle}
.tlf.lg{height:40px;width:40px;font-size:12px}.tlf.sm{height:18px;width:18px;font-size:7px}
.teams{display:flex;align-items:center;gap:11px}
.pitchers{display:flex;align-items:center;gap:14px;margin:11px 0 4px;flex-wrap:wrap}
.pcell{display:flex;align-items:center;gap:9px}
.phead{width:42px;height:42px;border-radius:50%;object-fit:cover;object-position:center top;background:var(--raised);
border:2px solid #454B61;box-shadow:0 5px 14px rgba(0,0,0,.45),0 0 0 2px rgba(154,107,255,.12)}
.phead-na{background:linear-gradient(160deg,var(--raised),var(--card))}.phead-na::after{content:"";display:block}
.pmeta{line-height:1.3}.pmeta b{color:var(--ink);font-size:14px}.pmeta span{display:block;color:var(--muted);font-size:11.5px}
.vsx{color:var(--muted-2);font:700 11px var(--display);text-transform:uppercase}
/* strip chips */
.strip{display:grid;grid-template-columns:repeat(8,1fr);gap:9px}
@media(max-width:880px){.strip{grid-template-columns:repeat(4,1fr)}}
.chipc{background:var(--raised);border:1px solid var(--border);border-radius:8px;padding:9px 10px;text-align:center}
.chipc .k{color:var(--muted);font-size:9.5px;text-transform:uppercase;letter-spacing:.06em;font-weight:800}
.chipc .v{color:var(--ink);font-family:var(--display);font-weight:800;font-size:19px;margin-top:3px}
.vbar{display:flex;align-items:center;gap:14px;padding:11px 16px;border-radius:8px;border:1px solid var(--border-2);font-size:13.5px;background:var(--card)}
.vbar b{font-family:var(--display);font-weight:800;font-size:15px;letter-spacing:.03em}.vbar span{color:var(--ink2)}
.vbar.pos{border-color:rgba(60,203,127,.3);background:rgba(60,203,127,.10)}.vbar.pos b{color:#7BDC5A}
.vbar.warnc{border-color:rgba(232,194,74,.3);background:rgba(232,194,74,.10)}.vbar.warnc b{color:var(--gold)}
.vbar.neg{border-color:rgba(242,84,91,.3);background:rgba(242,84,91,.10)}.vbar.neg b{color:#FCA5A5}
.vbar.mut b{color:var(--muted)}
.cols{display:grid;grid-template-columns:1fr 1fr;gap:14px;align-items:start;margin-top:14px}@media(max-width:760px){.cols{grid-template-columns:1fr}}
.note{color:var(--muted);font-size:11.5px;margin-top:8px}
.rtabs{margin-top:20px}
.rtabbar{display:flex;gap:2px;border-bottom:1px solid var(--border);flex-wrap:wrap;margin-bottom:14px}
.rtabbar button{padding:9px 16px;font:700 13.5px var(--sans);color:var(--muted);cursor:pointer;border:0;border-bottom:2.5px solid transparent;margin-bottom:-1px;background:none}
.rtabbar button:hover{color:var(--ink2)}.rtabbar button.on{color:var(--ink);border-bottom-color:var(--accent)}.pn{display:none}.pn.on{display:block}
th[title],td[title]{cursor:help;text-decoration:underline dotted rgba(148,163,184,.4);text-underline-offset:3px}
/* section */
.sec{border:1px solid var(--border-2);border-radius:8px;background:var(--card);overflow:hidden;position:relative}
.sec::before{content:"";position:absolute;top:0;left:0;right:0;height:2px;background:var(--v-grad);opacity:.6}
.sec h2{font-family:var(--display);font-weight:800;font-size:13px;letter-spacing:.06em;text-transform:uppercase;color:var(--v-light);margin:0;padding:13px 16px 0}
.sec .body{padding:12px 16px 16px}
.table-scroll{width:100%;overflow-x:auto}
/* tables */
table{width:100%;border-collapse:collapse}
th{color:var(--ink2);font-size:11px;letter-spacing:.05em;text-transform:uppercase;font-weight:800;text-align:right;padding:9px 12px;border-bottom:1px solid var(--border-2);white-space:nowrap}
th:first-child{text-align:left}
td{padding:9px 12px;text-align:right;border-bottom:1px solid rgba(255,255,255,.06);font-size:14px}
td:first-child{text-align:left;font-weight:600}tbody tr:last-child td{border-bottom:none}tbody tr:hover td{background:rgba(124,77,255,.08)}
.chip{font-family:var(--display);font-weight:800}
.pill{display:inline-block;padding:3px 10px;border-radius:999px;font-size:10.5px;font-weight:800;letter-spacing:.04em;border:1px solid transparent}
.pill.pos{background:rgba(60,203,127,.13);color:#7BDC5A;border-color:rgba(60,203,127,.22)}
.pill.warnc{background:rgba(232,194,74,.12);color:var(--gold);border-color:rgba(232,194,74,.22)}
.pill.neg{background:rgba(242,84,91,.12);color:#FCA5A5;border-color:rgba(242,84,91,.22)}
.pill.mut{background:rgba(255,255,255,.06);color:var(--ink2)}
/* comparison + driver bars */
.dbar{display:inline-block;width:64px;height:7px;border-radius:4px;background:rgba(255,255,255,.07);vertical-align:middle;overflow:hidden}
.dbar i{display:block;height:100%;border-radius:4px}
.delta{font-size:11px;font-weight:700}.n{color:var(--muted-2);font-size:10px;font-weight:600}
/* market-vs-model bars */
.mmwrap{display:flex;flex-direction:column;gap:7px}.mm{display:flex;align-items:center;gap:9px}
.mml{flex:0 0 96px;font-size:12px;color:var(--ink2)}.mmbar{position:relative;flex:1;height:12px;background:rgba(255,255,255,.06);border-radius:4px}
.mmbar i.mod{position:absolute;left:0;top:0;height:100%;background:var(--teal);border-radius:4px;opacity:.55}
.mmbar i.imp{position:absolute;top:-2px;width:2px;height:16px;background:#fff}.mmv{flex:0 0 46px;text-align:right;font-weight:700;font-size:12px}
/* arsenal */
.arshd{font-size:11px;color:var(--ink2);font-weight:700;margin:2px 0 6px}.ars{display:flex;flex-direction:column;gap:5px}
.arl{display:flex;align-items:center;gap:8px;font-size:11.5px}.apt{flex:0 0 34px;color:var(--muted);font-weight:700}
.abar{flex:1;height:8px;background:rgba(255,255,255,.06);border-radius:3px;overflow:hidden}.abar i{display:block;height:100%;background:var(--accent);border-radius:3px}
.apv{flex:0 0 32px;text-align:right;font-weight:700}.aw{flex:0 0 50px;text-align:right;color:var(--muted-2);font-size:10px}
.mvrow{display:flex;align-items:center;gap:9px;font-size:13px}.mvrow b{font-family:var(--display)}.mvarrow{color:var(--muted)}
.advbar{display:flex;align-items:center;gap:8px;justify-content:flex-end}
.advbar .seg{height:8px;border-radius:3px}.advbar .a{background:#9A6BFF}.advbar .h{background:#2dd4bf}
/* charts */
.charts{display:grid;grid-template-columns:1fr 1fr;gap:14px}@media(max-width:880px){.charts{grid-template-columns:1fr}}
.cap{display:flex;justify-content:space-between;font-size:11px;font-weight:700;margin-top:3px}
/* drawer */
details{border-top:1px solid var(--border);padding:12px 16px}summary{cursor:pointer;color:var(--ink2);font-weight:700;font-size:13px;list-style:none}
summary::before{content:"▸ ";color:var(--accent)}details[open] summary::before{content:"▾ "}
details ul{margin:8px 0 0;padding-left:18px}details li{font-size:12.5px;color:var(--muted);margin:4px 0}
/* decision-first matchup */
.matchup-head{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:18px;padding:4px 0 14px;border-bottom:1px solid var(--border)}
.matchup-team{display:flex;align-items:center;gap:10px}.matchup-team.home{justify-content:flex-end;text-align:right}
.matchup-team b{display:block;font:800 26px var(--display)}.matchup-team span{display:block;color:var(--muted);font-size:12px;margin-top:2px}
.score-projection{text-align:center}.score-projection span,.score-projection i{display:block;color:var(--muted);font-size:10px;font-style:normal;text-transform:uppercase}
.score-projection b{display:block;font:800 25px var(--display);margin:3px 0}
.decision-strip{display:grid;grid-template-columns:repeat(6,1fr);border:1px solid var(--border-2);border-radius:8px;margin:10px 0;overflow:hidden}
.decision-strip span{padding:10px 12px;border-right:1px solid var(--border);color:var(--muted);font-size:10px;text-transform:uppercase}
.decision-strip span:last-child{border-right:0}.decision-strip b{display:block;color:var(--ink);font:800 17px var(--display);text-transform:none;margin-bottom:2px}
.availability{display:flex;gap:1px;background:var(--border);border:1px solid var(--border);border-radius:8px;overflow:hidden;margin-bottom:12px}
.availability span{flex:1;background:var(--card);padding:9px 11px;color:var(--ink2);font-size:11px}
.availability b{display:block;color:var(--muted);font-size:9px;text-transform:uppercase;margin-bottom:2px}.availability i{font-style:normal;font-weight:800}
.decision-grid{display:grid;grid-template-columns:1.45fr 1fr;gap:12px;margin:12px 0}.missing-row{display:flex;align-items:center;gap:6px;flex-wrap:wrap;margin-top:10px}
.missing-row>b{color:var(--muted);font-size:10px;text-transform:uppercase;margin-right:3px}
.pitcher-grid{display:grid;grid-template-columns:1fr;gap:12px;margin:12px 0}
.pitch-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:var(--border);border:1px solid var(--border);border-radius:6px;overflow:hidden;margin-bottom:9px}
.pitch-summary span{background:var(--raised);padding:8px;color:var(--muted);font-size:10px;text-transform:uppercase}
.pitch-summary b,.pitch-summary em{display:block;color:var(--ink);font:800 17px var(--display);font-style:normal}
.pitch-summary i{display:block;color:var(--muted);font-size:9px;font-style:normal;text-transform:none}
.pitch-source{color:var(--muted);font-size:10px;margin-bottom:7px}.model-details{border:1px solid var(--border);border-radius:8px;margin-top:12px}
.pitch-name-meta{display:block;font-size:10px;margin-top:2px}
.model-details p{color:var(--muted);font-size:12px;line-height:1.5;max-width:1000px}
@media(max-width:980px){.decision-strip{grid-template-columns:repeat(3,1fr)}.decision-grid,.pitcher-grid{grid-template-columns:1fr}}
@media(max-width:680px){.matchup-head{grid-template-columns:1fr auto 1fr}.matchup-team b{font-size:20px}.matchup-team span{display:none}.score-projection b{font-size:18px}.decision-strip{grid-template-columns:repeat(2,1fr)}.availability{display:grid;grid-template-columns:1fr 1fr}.pitch-summary{grid-template-columns:repeat(2,1fr)}}
"""


def _td_signed(v, suffix="", good_pos=True):
    if v is None:
        return '<td class="mut">—</td>'
    tone = "pos" if (v > 0) == good_pos else "neg"
    if v == 0:
        tone = "mut"
    return f'<td class="{tone}">{v:+g}{suffix}</td>'


def _legacy_report_body(r):
    """Inner report content (no <html>/<style> wrapper) so the app shell can embed it."""
    gd, p, e = r["gd"], r["probs"], html.escape
    sd_t = r["anchors"]["team_sd"]
    w = gd.weather or {}
    wx = ("Dome" if w.get("dome")
          else f"{w['temp_f']:.0f}°F · {w.get('wind_mph', 0):.0f}mph" if w.get("temp_f") is not None
          else "weather n/a")

    # projection strip
    best_edge = max((m["edge"] for m in r["markets"] if m["edge"] is not None), default=None)
    strip = [
        ("Win %", f'<span class="side">{e(gd.away)} {p.p_away_win*100:.0f}</span> / <span class="pos">{e(gd.home)} {p.p_home_win*100:.0f}</span>'),
        ("Proj score", f'{e(gd.away)} {p.exp_away_runs:.1f} / {e(gd.home)} {p.exp_home_runs:.1f}'),
        ("Proj total", f'{p.exp_total:.1f}'),
        ("Total 10–90", f'{r["simulation"].total_p10:.0f}–{r["simulation"].total_p90:.0f}'),
        ("Mkt total", (f'{r["posted_total"]:.1f}' if r.get("posted_total") else '—')),
        (f"Fair {gd.home} ML", f'{fair_price(p.p_home_win):+d}'),
        ("Best edge", (f'<span class="{"pos" if best_edge and best_edge>0 else "mut"}">{best_edge:+.1f}pt</span>' if best_edge is not None else "—")),
        ("Status", f'<span class="warnc">{e(r["confidence"])}</span>'),
    ]
    strip_html = "".join(f'<div class=chipc><div class=k>{e(k)}</div><div class=v>{v}</div></div>' for k, v in strip)

    # market grid
    def mrow(m):
        mkt = f'{m["mkt"]:+d}' if m["mkt"] is not None else "—"
        impl = f'{m["impl"]}%' if m["impl"] is not None else "—"
        return (f'<tr><td>{e(m["label"])}</td>'
                f'<td title="{e((m.get("book") or "no book") + " · " + str(m.get("books", 0)) + " paired books")}">{mkt}</td>'
                f'<td>{m["fair"]:+d}</td>'
                f'<td>{impl}</td>'
                f'<td>{m["model"]}%</td>'
                f'{_td_signed(m["edge"], "pt")}'
                f'{_td_signed(m["ev"], "")}'
                f'<td>{m["max"]:+d}</td>'
                f'<td title="{e(m.get("reason") or "")}"><span class="pill {m["tone"]}">{m["state"]}</span></td></tr>')
    mrows = "".join(mrow(m) for m in r["markets"])

    # advantage matrix
    def _delta(d, lower_better):
        if d is None:
            return ""
        good = (d < 0) if lower_better else (d > 0)
        tone = "pos" if good else ("neg" if d != 0 else "mut")
        return f' <span class="delta {tone}">{d:+g}</span>'

    def arow(a):
        ac, al = _chip(a["a_pct"])
        hc, hl = _chip(a["h_pct"])
        u, lb = a["unit"], a["lower_better"]
        ar = f' <span class=n>#{a["a_rank"]}</span>' if a.get("a_rank") else ''
        hr = f' <span class=n>#{a["h_rank"]}</span>' if a.get("h_rank") else ''
        # stat-presentation standard: raw + Δ-vs-baseline + percentile chip + rank, per team
        av = f'{_f(a["a_val"])}{u}{_delta(a["a_d"], lb)} <span class="chip {ac}">{al}</span>{ar}'
        hv = f'{_f(a["h_val"])}{u}{_delta(a["h_d"], lb)} <span class="chip {hc}">{hl}</span>{hr}'
        n = f' <span class=n>n={a["n"]}</span>' if a.get("n") else ''
        role = "model input" if a["role"] == "modeled" else "context"
        return (f'<tr><td title="{e(_cat_def(a["cat"]))}">{e(a["cat"])}{n}</td>'
                f'<td class=side>{av}</td><td class=pos>{hv}</td>'
                f'<td class=mut>{_f(a["base"])}{u}</td>'
                f'<td>{e(str(a["edge"]))}</td><td class=mut>{e(role)}</td></tr>')
    arows = "".join(arow(a) for a in r["advantage"])

    # key drivers (ranked contribution bars)
    def drow(f_):
        tone = "pos" if f_["runs"] > 0 else "neg"
        lineage = "MLBMA" if f_["source"].startswith("MLBMA") else "Empirical"
        return (f'<tr><td>{e(f_["name"])}</td>'
                f'<td>{_bar(f_["pct"], tone)} <span class="{tone}">{f_["pct"]:+.1f}%</span></td>'
                f'<td class="{tone}">{f_["runs"]:+.2f} R</td><td>{e(f_["side"])}</td>'
                f'<td>{e(f_["conf"])}</td><td class=mut>{e(f_["market"])}</td>'
                f'<td class=mut title="{e(f_["source"])}">{lineage}</td></tr>')
    drows = "".join(drow(f_) for f_ in r["factors"])

    sharp = (r["sharp"] and "".join(
        f'<tr><td>{e(s["market_type"])}</td><td>{e(str(s["selection"]))}</td>'
        f'{_td_signed(round(float(s.get("divergence") or 0)*100,1),"pt")}'
        f'<td>{"STEAM" if s.get("steam_flag") else "—"}</td></tr>' for s in r["sharp"])) \
        or '<tr><td class=mut colspan=4>No sharp signal recorded.</td></tr>'
    def risk_tone(signal):
        return "neg" if signal.severity == "high" else "warnc"

    rrows = "".join(
        f'<tr><td>{e(signal.label)}</td><td>{e(signal.implication)}</td>'
        f'<td><span class="pill {risk_tone(signal)}">{e(signal.category)}</span></td></tr>'
        for signal in r["risks"]
    ) or '<tr><td class=mut colspan=3>None flagged.</td></tr>'

    # top verdict bar — the single most decision-relevant line, above the fold
    op = max((m for m in r["markets"] if m["edge"] is not None), key=lambda m: m["edge"], default=None)
    if op and op["edge"] > 0 and op["state"] in ("BET", "MONITOR", "REVIEW"):
        vb = (f'<div class="vbar {op["tone"]}"><b>{op["state"]}</b>'
              f'<span>{e(op["label"])}</span><span>edge {op["edge"]:+.1f}pt</span>'
              f'<span>EV {op["ev"]:+.3f}</span><span>max {op["max"]:+d}</span>'
              f'<span>{e(op["reason"])}</span></div>')
    else:
        has_price = any(market["mkt"] is not None for market in r["markets"])
        message = (
            "No positive executable edge"
            if has_price else "Paired market prices unavailable; no action can be evaluated"
        )
        vb = f'<div class="vbar mut"><b>NO EDGE</b><span>{e(message)}</span></div>'

    # Decision layer only uses factors that actually changed the projection.
    why = "".join(
        f'<tr><td>{e(factor["name"])}</td><td class={"pos" if factor["runs"] > 0 else "neg"}>'
        f'{factor["runs"]:+.2f} R</td><td class=mut>{e(factor["market"])}</td></tr>'
        for factor in r["factors"][:3]
    ) or '<tr><td class=mut colspan=3>No modeled driver.</td></tr>'
    rtop = "".join(
        f'<tr><td>{e(signal.label)}</td><td class=mut>{e(signal.implication)}</td></tr>'
        for signal in r["risks"][:2]
    ) or '<tr><td class=mut colspan=2>None flagged.</td></tr>'
    # incomplete-data flag
    miss = [n for n, v in (("weather", (gd.weather or {}).get("temp_f")),
                           ("lineups", "posted" in r["extras"]["lineup"])) if not v]
    dq = f'<span class="pill warnc" title="default view omits unavailable inputs">incomplete: {", ".join(miss)}</span>' if miss else ''

    fresh_hours = r.get("freshness_hours")
    fresh = fresh_hours is not None and fresh_hours <= 18
    freshness_label = (
        f"data {fresh_hours:.1f}h old" if fresh_hours is not None else "data timestamp unavailable"
    )
    return f"""<div class=hd>
   <div style="min-width:0">
     <div class=teams>{_logo(r['away'],'tlogo lg')}<h1>{e(r['away'])} <span class=mut style="font:inherit">@</span> {e(r['home'])}</h1>{_logo(r['home'],'tlogo lg')}</div>
     <div class=pitchers>
       <div class=pcell>{_headshot(r['extras'].get('a_id'))}<div class=pmeta><b>{e(gd.away_sp)}</b><span>{e(gd.away_hand)}HP · FIP {gd.away_fip}</span></div></div>
       <span class=vsx>vs</span>
       <div class=pcell>{_headshot(r['extras'].get('h_id'))}<div class=pmeta><b>{e(gd.home_sp)}</b><span>{e(gd.home_hand)}HP · FIP {gd.home_fip}</span></div></div>
     </div>
     <div class=sp>{e(r['extras']['start'] or 'TBD')} · {e(gd.home)} park {gd.park_factor} · {e(wx)} · {e(r['extras']['lineup'])}</div></div>
	   <div class=meta><span class={"fresh" if fresh else "warnc"}>● {e(freshness_label)}</span><br>model {e(r['model_version'])} · metrics {e(r['metric_version'])}<br>{e(r['generated'][:16])}Z · game {r['game_pk']}</div>
 </div>

 {vb}
 <div class=strip>{strip_html}</div>

 <!-- DECISION LAYER: clearest edges + biggest risks, always visible -->
 <div class=cols>
	   <div class=sec><h2>Modeled drivers</h2><div class=body>
	     <table><tr><th>Factor</th><th>Run impact</th><th>Affects</th></tr>{why}</table></div></div>
	   <div class=sec><h2>Top risks {dq}</h2><div class=body>
	     <table><tr><th>Signal</th><th>Implication</th></tr>{rtop}</table>
     <div class=note>Full evidence in the tabs below; definitions on hover.</div></div></div>
 </div>

	 <!-- ANALYSIS LAYER: one tab at a time (not a wall of data) -->
	 <div class=rtabs>
	   <div class=rtabbar>
	     <button class=on onclick="showReportTab(this,'markets')">Markets</button>
	     <button onclick="showReportTab(this,'charts')">Charts</button>
	     <button onclick="showReportTab(this,'matchup')">Matchup</button>
	     <button onclick="showReportTab(this,'drivers')">Drivers</button>
	     <button onclick="showReportTab(this,'sharp')">Sharp</button>
	   </div>
	   <div class=rpanels>
	     <div data-panel=markets class="pn on"><div class=sec><div class=body><div class=table-scroll>
	       <table><tr><th>Market</th><th title="best available American price">Mkt</th><th title="model fair price">Fair</th><th title="paired, de-vigged market consensus">Mkt no-vig</th><th title="model probability">Model</th><th title="model% minus no-vig market%">Edge</th><th title="expected value at the executable price">EV/u</th><th title="break-even price">Max</th><th>State</th></tr>{mrows}</table></div>
	       <div class=note>BET is impossible until the governing strategy passes the promotion gate. MONITOR is research, not a wager instruction.</div></div></div></div>
	     <div data-panel=charts class=pn><div class=charts>
       <div class=sec><h2>Win prob</h2><div class=body>{_svg_winprob(p.p_home_win,p.p_away_win,e(r['home']),e(r['away']))}</div></div>
       <div class=sec><h2>Run distribution</h2><div class=body>{_svg_rundist(p.exp_away_runs,p.exp_home_runs,sd_t,e(r['away']),e(r['home']))}</div></div>
       <div class=sec><h2>Model vs market</h2><div class=body>{_svg_mktmodel(r['markets'])}</div></div>
       <div class=sec><h2>Total sensitivity</h2><div class=body>{_svg_scenario(r['extras']['scenario'], r.get('posted_total'))}</div></div>
       <div class=sec><h2>SP arsenals</h2><div class=body>{_svg_arsenal(r['extras']['arsenal_a'], e(gd.away_sp))}<div style="height:8px"></div>{_svg_arsenal(r['extras']['arsenal_h'], e(gd.home_sp))}</div></div>
       <div class=sec><h2>Line movement</h2><div class=body>{_svg_movement(r['movement'])}</div></div>
     </div></div>
	     <div data-panel=matchup class=pn><div class=sec><div class=body><div class=table-scroll>
	       <table><tr><th>Category</th><th>{e(r['away'])}</th><th>{e(r['home'])}</th><th title="MLB league average">MLB</th><th>Edge</th><th>Impact</th></tr>{arows}</table>
	       </div><div class=note>Rows marked context do not change the current projection. They remain visible for research without being misrepresented as model drivers.</div></div></div></div>
	     <div data-panel=drivers class=pn><div class=sec><div class=body>
	       <table><tr><th>Factor</th><th title="% multiplier change">Effect</th><th>Runs</th><th>Side</th><th>Confidence</th><th>Markets</th><th>Lineage</th></tr>{drows}</table></div></div></div>
	     <div data-panel=sharp class=pn>
       <div class=sec><h2>Sharp money</h2><div class=body>
         <table><tr><th>Market</th><th>Side</th><th title="sharp minus soft de-vig probability">Divergence</th><th>Steam</th></tr>{sharp}</table></div></div>
	       <div class=sec><h2>Risks</h2><div class=body>
	         <table><tr><th>Signal</th><th>Implication</th><th>Type</th></tr>{rrows}</table></div></div>
     </div>
   </div>
 </div>

 <div class=sec><details><summary>Methodology &amp; definitions</summary><ul>
	   <li><b>Model</b> = expected-runs prior (offense OSI × opposing SP FIP × park × bullpen, regressed to mean); anchors from settled finals. <b>Fair</b> price from that probability; <b>Edge</b> = model − vig-free market; <b>EV</b> net of vig.</li>
	   <li><b>Total 10–90</b> = the middle 80% of 25,000 deterministic negative-binomial challenger simulations using settled team-run variance. It describes score uncertainty and has no betting authority.</li>
   <li><b>OSI</b> offense strength index (50 = avg). <b>FIP</b> fielding-independent ERA. <b>wOBA</b> weighted on-base. <b>OBR</b> baserunning index. Percentiles empirical vs the league.</li>
	   <li><b>Promotion gate:</b> {e(r["promotion"].get("verdict", "HOLD/ABSTAIN"))}. Unpromoted signals can only be MONITOR or AVOID. Observed context, modeled inputs, and market prices are kept distinct.</li></ul></details></div>
"""


def report_body(r):
    """Render a matchup as a betting decision surface, not a written report."""
    gd, probability, esc = r["gd"], r["probs"], html.escape
    context = gd.live_context or {}
    lineups = context.get("lineups") or {}
    weather = context.get("weather") or {}
    umpire = context.get("umpire") or {}
    travel = context.get("travel") or {}

    def market_row(market):
        market_price = (
            f'{market["mkt"]:+d}' if market["mkt"] is not None else "—"
        )
        market_probability = (
            f'{market["impl"]:.1f}%' if market["impl"] is not None else "—"
        )
        edge = (
            f'{market["edge"]:+.1f}pt' if market["edge"] is not None else "—"
        )
        ev = f'{market["ev"] * 100:+.1f}%' if market["ev"] is not None else "—"
        tone = "pos" if (market.get("edge") or 0) > 0 else (
            "neg" if market.get("edge") is not None else "mut"
        )
        return (
            f'<tr><td><b>{esc(market["label"])}</b></td><td>{market_price}</td>'
            f'<td>{market["fair"]:+d}</td><td>{market_probability}</td>'
            f'<td>{market["model"]:.1f}%</td><td class={tone}>{edge}</td>'
            f'<td class={tone}>{ev}</td><td><span class="pill {market["tone"]}">'
            f'{esc(market["state"])}</span></td></tr>'
        )

    market_rows = "".join(market_row(market) for market in r["markets"])
    opportunity = max(
        (market for market in r["markets"] if market["edge"] is not None),
        key=lambda market: market["edge"],
        default=None,
    )
    if opportunity and opportunity["edge"] > 0:
        decision = (
            f'<div class="vbar {opportunity["tone"]}"><b>{opportunity["state"]}</b>'
            f'<span>{esc(opportunity["label"])}</span>'
            f'<span>model {opportunity["model"]:.1f}%</span>'
            f'<span>market {opportunity["impl"]:.1f}%</span>'
            f'<span>edge {opportunity["edge"]:+.1f}pt</span></div>'
        )
    else:
        reason = (
            "No positive priced edge"
            if any(market["mkt"] is not None for market in r["markets"])
            else "No paired market snapshot"
        )
        decision = f'<div class="vbar mut"><b>NO ACTION</b><span>{esc(reason)}</span></div>'

    weather_label = "Dome"
    if weather.get("status") != "dome":
        temperature = weather.get("temperature_f")
        wind_out = weather.get("wind_out_mph")
        rain = weather.get("precipitation_probability_pct")
        weather_label = (
            f'{temperature:.0f}°F · wind {"out" if (wind_out or 0) >= 0 else "in"} '
            f'{abs(wind_out or 0):.0f} mph · rain {rain or 0:.0f}%'
            if temperature is not None else "Unavailable"
        )
    away_lineup = (lineups.get("away") or {}).get("status", "unavailable")
    home_lineup = (lineups.get("home") or {}).get("status", "unavailable")
    umpire_label = (
        umpire.get("umpire")
        if umpire.get("status") == "announced"
        else "Not announced"
    )
    coverage_tone = "pos" if probability.data_coverage_pct >= 85 else "warnc"
    availability = (
        f'<div class=availability>'
        f'<span><b>{esc(gd.away)} lineup</b>{esc(away_lineup)}</span>'
        f'<span><b>{esc(gd.home)} lineup</b>{esc(home_lineup)}</span>'
        f'<span><b>First pitch</b>{esc(weather_label)}</span>'
        f'<span><b>Plate umpire</b>{esc(str(umpire_label))}</span>'
        f'<span><b>Input coverage</b><i class={coverage_tone}>'
        f'{probability.data_coverage_pct}%</i></span></div>'
    )

    factor_rows = "".join(
        f'<tr><td><b>{esc(factor["name"])}</b><span class=mut>'
        f' · {esc(factor["side"])}</span></td>'
        f'<td class={"pos" if factor["runs"] > 0 else "neg"}>'
        f'{factor["runs"]:+.2f} runs</td>'
        f'<td>{esc(factor["market"])}</td>'
        f'<td><span class="pill {"warnc" if factor["conf"] == "low" else "mut"}">'
        f'{esc(factor["conf"])}</span></td></tr>'
        for factor in r["factors"][:6]
    )
    missing = "".join(
        f'<span class="pill warnc">{esc(item)}</span>'
        for item in probability.missing_context
    ) or '<span class="pill pos">core context loaded</span>'

    def team_value_rows():
        away_starter = gd.away_starter_features
        home_starter = gd.home_starter_features
        away_pen = gd.away_bullpen_features
        home_pen = gd.home_bullpen_features
        away_line = gd.away_lineup_features
        home_line = gd.home_lineup_features
        away_travel = travel.get("away") or {}
        home_travel = travel.get("home") or {}
        away_injury = gd.away_injury_features
        home_injury = gd.home_injury_features

        def line_value(value):
            if value.get("status") not in {"confirmed", "projected"}:
                return "Not posted"
            return (
                f'{value.get("projected_osi", "—")} vs '
                f'{value.get("team_baseline_osi", "—")} baseline'
            )

        def travel_value(value):
            if value.get("status") != "available":
                return "No recent game"
            return (
                f'{value.get("rest_hours", 0):.1f}h rest · '
                f'{value.get("travel_miles", 0):.0f} mi'
            )

        def injury_value(value):
            players = value.get("impact_players") or []
            if not players:
                return "No quantified hitter loss"
            return ", ".join(player["player"] for player in players[:3])

        rows = [
            (
                "Starter expected level",
                f'{away_starter.get("skill_fip", settings.LEAGUE_FIP):.2f} runs/9 scale',
                f'{home_starter.get("skill_fip", settings.LEAGUE_FIP):.2f} runs/9 scale',
                "Lower is better",
            ),
            (
                "Starter workload",
                f'{away_starter.get("expected_ip", 5.2):.1f} projected innings',
                f'{home_starter.get("expected_ip", 5.2):.1f} projected innings',
                "Shapes bullpen exposure and outs props",
            ),
            (
                "Bullpen quality",
                f'{away_pen.get("skill_fip", settings.LEAGUE_BULLPEN_ERA):.2f} · '
                f'{away_pen.get("pitches_1d") or 0:.0f} pitches yesterday',
                f'{home_pen.get("skill_fip", settings.LEAGUE_BULLPEN_ERA):.2f} · '
                f'{home_pen.get("pitches_1d") or 0:.0f} pitches yesterday',
                "Lower quality number and fresher workload are better",
            ),
            (
                "Lineup vs starter hand",
                line_value(away_line),
                line_value(home_line),
                "Posted batting order versus the opposing starter's hand",
            ),
            (
                "Unavailable hitters",
                injury_value(away_injury),
                injury_value(home_injury),
                "Only quantified before confirmed lineups; then lineup absorbs it",
            ),
            (
                "Rest and travel",
                travel_value(away_travel),
                travel_value(home_travel),
                "Short rest, distance, and timezone shift",
            ),
        ]
        return "".join(
            f'<tr><td><b>{esc(label)}</b></td><td>{esc(away_value)}</td>'
            f'<td>{esc(home_value)}</td><td class=mut>{esc(context_note)}</td></tr>'
            for label, away_value, home_value, context_note in rows
        )

    matchup_rows = team_value_rows()

    def pitcher_panel(team):
        pitcher = next(
            (row for row in r.get("pitchers", []) if row.get("team") == team),
            None,
        )
        if not pitcher or not pitcher.get("projections"):
            return (
                f'<div class=sec><h2>{esc(team)} starter</h2><div class=body>'
                f'<div class=empty>No matched pitcher projection.</div></div></div>'
            )
        projections = pitcher["projections"]
        pitch_matchup = pitcher.get("pitch_matchup") or {}
        pitch_rows = "".join(
            f'<tr><td><b>{esc(str(pitch["pitch"]))}</b>'
            f'<span class="mut pitch-name-meta">{pitch["usage_pct"]:.0f}% usage</span></td>'
            f'<td>{pitch["lineup_xwoba"]:.3f}</td>'
            f'<td>{pitch["lineup_whiff_pct"]:.1f}%</td>'
            f'<td class={"pos" if pitch["k_delta"] > 0 else "neg"}>'
            f'{pitch["k_delta"]:+.2f} K%</td>'
            f'<td class={"pos" if pitch["er_factor_delta"] < 0 else "neg"}>'
            f'{pitch["er_factor_delta"] * 100:+.1f}% runs</td>'
            f'<td>{esc(pitch["edge"])}</td></tr>'
            for pitch in pitch_matchup.get("pitches", [])[:5]
        ) or '<tr><td class=mut colspan=6>No reliable pitch overlap.</td></tr>'
        state_tone = "neg" if pitcher["state"] == "REGRESSION" else (
            "pos" if pitcher["state"] == "PROGRESSION" else (
                "warnc" if pitcher["state"] == "LIMITED SAMPLE" else "side"
            )
        )
        return f"""<div class=sec><h2>{esc(str(pitcher["pitcher"]))} vs {esc(str(pitcher["opponent"]))}</h2>
          <div class=body>
            <div class=pitch-summary>
              <span><b>{projections["K"]["mean"]:.1f}</b>K <i>{projections["K"]["p10"]:.0f}–{projections["K"]["p90"]:.0f}</i></span>
              <span><b>{projections["ER"]["mean"]:.1f}</b>ER <i>{projections["ER"]["p10"]:.0f}–{projections["ER"]["p90"]:.0f}</i></span>
              <span><b>{projections["Outs"]["mean"]:.1f}</b>outs <i>{projections["Outs"]["p10"]:.0f}–{projections["Outs"]["p90"]:.0f}</i></span>
              <span><em class={state_tone}>{esc(pitcher["state"])}</em><i>{esc(pitcher["confidence"])} confidence</i></span>
            </div>
            <div class=pitch-source>{esc(str(pitch_matchup.get("response_source") or "No response source"))} · expected contact below .320 favors the pitcher</div>
            <div class=table-scroll><table><tr><th>Pitch</th><th>Opponent expected contact</th>
              <th>Opponent whiff</th><th>K effect</th><th>Run effect</th><th>Edge</th></tr>{pitch_rows}</table></div>
          </div></div>"""

    pitcher_panels = pitcher_panel(gd.away) + pitcher_panel(gd.home)
    risk_rows = "".join(
        f'<tr><td><b>{esc(signal.label)}</b></td>'
        f'<td>{esc(signal.implication)}</td>'
        f'<td><span class="pill {"neg" if signal.severity == "high" else "warnc"}">'
        f'{esc(signal.category)}</span></td></tr>'
        for signal in r["risks"][:5]
    ) or '<tr><td class=mut colspan=3>No additional risk flags.</td></tr>'
    sharp_rows = "".join(
        f'<tr><td>{esc(signal["market_type"])}</td><td>{esc(str(signal["selection"]))}</td>'
        f'<td>{float(signal.get("divergence") or 0) * 100:+.1f}pt</td>'
        f'<td>{"STEAM" if signal.get("steam_flag") else "—"}</td></tr>'
        for signal in r["sharp"]
    ) or '<tr><td class=mut colspan=4>No sharp-money snapshot for this game.</td></tr>'

    fresh_hours = r.get("freshness_hours")
    freshness = (
        f"{fresh_hours:.1f}h old" if fresh_hours is not None else "timestamp unavailable"
    )
    return f"""<div class=matchup-head>
      <div class=matchup-team>{_logo(gd.away, "tlogo lg")}<div><b>{esc(gd.away)}</b><span>{esc(gd.away_sp)}</span></div></div>
      <div class=score-projection><span>Projected score</span><b>{probability.exp_away_runs:.1f} – {probability.exp_home_runs:.1f}</b><i>{probability.exp_total:.1f} total</i></div>
      <div class=matchup-team home><div><b>{esc(gd.home)}</b><span>{esc(gd.home_sp)}</span></div>{_logo(gd.home, "tlogo lg")}</div>
    </div>
    {decision}
    <div class=decision-strip>
      <span><b>{probability.p_away_win * 100:.1f}%</b>{esc(gd.away)} win</span>
      <span><b>{probability.p_home_win * 100:.1f}%</b>{esc(gd.home)} win</span>
      <span><b>{fair_price(probability.p_home_win):+d}</b>fair {esc(gd.home)} ML</span>
      <span><b>{r["simulation"].total_p10:.0f}–{r["simulation"].total_p90:.0f}</b>80% total range</span>
      <span><b>{esc(probability.confidence)}</b>model confidence</span>
      <span><b>{esc(freshness)}</b>data age</span>
    </div>
    {availability}

    <div class=decision-grid>
      <div class=sec><h2>Market report</h2><div class=body><div class=table-scroll>
        <table><tr><th>Bet</th><th>Best</th><th>Fair</th><th>Market</th>
        <th>Model</th><th>Edge</th><th>EV</th><th>State</th></tr>{market_rows}</table>
      </div></div></div>
      <div class=sec><h2>Biggest run impacts</h2><div class=body>
        <div class=table-scroll><table><tr><th>Factor</th><th>Impact</th><th>Affects</th><th>Trust</th></tr>{factor_rows}</table></div>
        <div class=missing-row><b>Waiting on</b>{missing}</div>
      </div></div>
    </div>

    <div class=sec><h2>Matchup inputs</h2><div class=body><div class=table-scroll>
      <table><tr><th>What matters</th><th>{esc(gd.away)}</th><th>{esc(gd.home)}</th><th>Betting meaning</th></tr>
      {matchup_rows}</table></div></div></div>

    <div class=pitcher-grid>{pitcher_panels}</div>

    <div class=decision-grid>
      <div class=sec><h2>Sharp market activity</h2><div class=body><table>
        <tr><th>Market</th><th>Side</th><th>Sharp gap</th><th>Move</th></tr>{sharp_rows}</table>
      </div></div>
      <div class=sec><h2>What can break the projection</h2><div class=body><table>
        <tr><th>Risk</th><th>Betting implication</th><th>Type</th></tr>{risk_rows}</table>
      </div></div>
    </div>

    <details class=model-details><summary>Model lineage and limits</summary>
      <p>Runs are built sequentially from team offense, handedness, posted lineup, official injuries,
      rest/travel, starter innings and skill, bullpen quality and workload, park, first-pitch weather,
      and the announced plate umpire. Every visible impact above is the exact run change produced at
      that step. Missing inputs remain neutral and reduce confidence.</p>
      <p>Promotion gate: <b>{esc(r["promotion"].get("verdict", "HOLD/ABSTAIN"))}</b>.
      A positive projection-price gap remains MONITOR until executable out-of-sample results pass the gate.</p>
    </details>"""


def render_html(r):
    """Full standalone document (wraps report_body with the design-system stylesheet)."""
    e = html.escape
    script = (
        "function showReportTab(b,k){const r=b.closest('.rtabs');"
        "r.querySelectorAll('.rtabbar button').forEach(x=>x.classList.remove('on'));"
        "r.querySelectorAll('.pn').forEach(x=>x.classList.remove('on'));"
        "b.classList.add('on');r.querySelector('[data-panel=\"'+k+'\"]').classList.add('on');}"
    )
    return (f'<!DOCTYPE html><html lang=en><head><meta charset=utf-8>'
            f'<meta name=viewport content="width=device-width,initial-scale=1">'
            f'<title>{e(r["away"])}@{e(r["home"])} — MLB Model</title>'
            f'<style>{_CSS}</style></head><body><div class=wrap>{report_body(r)}</div>'
            f'<script>{script}</script></body></html>')


def main():  # pragma: no cover
    ap = argparse.ArgumentParser(description="Matchup Intelligence Report (terminal).")
    ap.add_argument("--game", required=True)
    ap.add_argument("--out", default="matchup_report.html")
    ap.add_argument("--no-fetch", action="store_true", help="use cached odds only (0 API credits)")
    args = ap.parse_args()
    away, home = (s.strip().upper() for s in args.game.split("@", 1))
    r = build_report(away, home, fetch=not args.no_fetch)
    open(args.out, "w", encoding="utf-8").write(render_html(r))
    print(f"wrote {args.out}  ({r['away']}@{r['home']})")


if __name__ == "__main__":
    main()
