"""
Matchup Intelligence Report — the canonical, scannable output of the unified MLB Model.

A research/trading TERMINAL, not a written report. It follows the Sharp Money Tracker / Chase
Analytics design system (violet, Roboto Condensed + tabular nums, percentile color chips
c-elite..c-poor, premium tables, comparison bars, inline SVG charts). Presentation order:
raw number -> visual context -> comparative meaning -> modeled implication -> (optional) explanation.

Powered by the unified expected-runs, paired-pricing, risk, MLBMA context, and warehouse
modules. Every modeled driver is generated by the probability calculation itself; descriptive
context is labeled separately.
"""
from __future__ import annotations

import argparse
import html
import math
from datetime import datetime, timezone

from mlbmodel import settings
from mlbmodel.baseball.model import (
    fair_price,
    market_probability,
    model_probabilities,
    normal_cdf,
    offense_factor,
    pitch_factor,
)
from mlbmodel.baseball.context import weather_run_factor
from mlbmodel.baseball.metrics import signal_edge_adjustment
from mlbmodel.baseball.repository import DataRepository
from mlbmodel.baseball.risk import risk_signals
from mlbmodel.baseball.simulation import simulate_game
from mlbmodel.market.oddsmath import prob_to_american
from mlbmodel.market.quotes import OddsBoard, load_board
from mlbmodel.market.value import assess_value
from mlbmodel.quant.promotion_gate import promotion_verdict
from mlbmodel.report.html_fmt import (
    edge_grade,
    pct_chip_html,
    prob_chip_html,
    section_head,
    val_chip_html,
    val_grade_html,
)
from mlbmodel.report.pitch_mix_ui import pitch_mix_runs_chip
from mlbmodel.report.matchup_ui import (
    advantage_panel_html,
    f5_section_html,
    matchup_banner_html,
    matchup_context_html,
    pitcher_deck_html,
    run_impacts_html,
)
from mlbmodel.storage.supabase import SupabaseReader


def _live_odds(fetch=True) -> OddsBoard:
    return load_board(fetch=fetch)


# ── visual identity: official MLB team logos + pitcher headshots (CDN) ───────
_MLB_ID = {"ARI": 109, "ATL": 144, "BAL": 110, "BOS": 111, "CHC": 112, "CHW": 145,
           "CIN": 113, "CLE": 114, "COL": 115, "DET": 116, "HOU": 117, "KCR": 118,
           "LAA": 108, "LAD": 119, "MIA": 146, "MIL": 158, "MIN": 142, "NYM": 121,
           "NYY": 147, "ATH": 133, "PHI": 143, "PIT": 134, "SDP": 135, "SFG": 137,
           "SEA": 136, "STL": 138, "TBR": 139, "TEX": 140, "TOR": 141, "WSN": 120}


def _logo(abbr, cls="tlogo"):
    a = str(abbr).upper().strip()
    i = _MLB_ID.get(a)
    if not i:
        return f'<span class="tlf {cls}">{html.escape(a)}</span>'
    return (f'<img class="{cls}" src="https://www.mlbstatic.com/team-logos/{i}.svg" '
            f'alt="" aria-hidden=true loading="lazy" '
            f'onerror="this.outerHTML=&quot;<span class=\'tlf {cls}\'>{html.escape(a)}</span>&quot;">')


def _headshot(pid):
    if not pid:
        return '<span class="phead phead-na"></span>'
    return (f'<img class=phead loading="lazy" alt="" '
            f'src="https://img.mlbstatic.com/mlb-photos/image/upload/d_people:generic:headshot:67:current.png/'
            f'w_120,q_auto:best/v1/people/{int(pid)}/headshot/67/current" '
            f'onerror="this.classList.add(&quot;phead-na&quot;)">')


# ── stat helpers (raw -> percentile -> semantic chip) ────────────────────────
def _cdf(z: float) -> float:
    return 0.5 * (1 + math.erf(z / math.sqrt(2)))


def _emp_pctile(series, value: float, lower_better: bool) -> float | None:
    """Empirical percentile of `value` within `series` (a pandas Series). 0..100."""
    try:
        import pandas as pd
        s = pd.to_numeric(series, errors="coerce").dropna()
        if s.empty or value is None:
            return None
        p = float((s < value).mean()) * 100
        return round(100 - p if lower_better else p, 0)
    except Exception:
        return None


def _chip(pct: float | None) -> tuple[str, str]:
    """Percentile -> (css class, label) using the Sharp Money Tracker scale."""
    if pct is None:
        return "c-na", "—"
    if pct >= 90:
        return "c-elite", "elite"
    if pct >= 70:
        return "c-good", "strong"
    if pct >= 40:
        return "c-mid", "avg"
    if pct >= 20:
        return "c-weak", "weak"
    return "c-poor", "poor"


def _f(v, nd=2):
    return f"{v:.{nd}f}" if isinstance(v, (int, float)) else "—"


_DEF = {
    "FIP": "Fielding-Independent Pitching — ERA from what a pitcher controls (K/BB/HR). Lower is better.",
    "K%": "Strikeout rate. Higher = more swings-and-misses, fewer balls in play.",
    "HR/9": "Home runs allowed per 9 innings. Lower is better.",
    "OSI": "Offense Strength Index (50 = league average). Higher = stronger lineup.",
    "ABQ": "At-Bat Quality. Higher indicates more consistently productive plate appearances.",
    "RCV": "Run Creation Value. Higher indicates stronger run-producing quality.",
    "PALS": "Pressure-Adjusted Lineup Strength. Higher indicates a stronger projected lineup.",
    "projOSI": "Projected Offense Strength Index for the expected lineup.",
    "wOBA": "Weighted On-Base Average — overall offensive value. Higher is better (~.320 avg).",
    "OBR": "Baserunning index (50 = average). Higher = better baserunning.",
    "Bullpen": "Relief run-prevention. Lower factor / ERA is better.",
    "Park": "Park run environment (1.00 = neutral; >1 boosts scoring).",
}


def _cat_def(cat):
    for k, v in _DEF.items():
        if k in cat:
            return v
    return ""


# ── factor decomposition (drivers) ───────────────────────────────────────────
def _factors(probs):
    out = [
        {
            "name": factor.name,
            "pct": round((factor.multiplier - 1) * 100, 1),
            "runs": round(factor.run_delta, 2),
            "side": factor.side,
            "market": factor.markets,
            "conf": factor.confidence,
            "source": factor.source,
        }
        for factor in probs.factors
    ]
    return sorted(out, key=lambda value: -abs(value["runs"]))


# ── advantage matrix (team vs team, with empirical percentiles + rank) ────────
def _rank(pct, n):
    """Rank (1 = best) implied by a percentile within n peers."""
    if pct is None or not n:
        return None
    return max(1, round((100 - pct) / 100 * n) + 1)


def _col(df, name):
    return df[name] if df is not None and name in df.columns else None


def _tv(idx, team, col):
    import pandas as pd
    r = idx.get(str(team).upper().strip())
    if r is None or col not in r:
        return None
    v = pd.to_numeric(r[col], errors="coerce")
    return None if pd.isna(v) else float(v)


def _advantage(gd, anchors, repo):
    import pandas as pd
    sp = repo.load("sp_profiles.csv")
    tp = repo.load("team_profiles.csv")
    fip_s, k_s, hr_s = _col(sp, "FIP"), _col(sp, "K_pct"), _col(sp, "HR9")
    osi_s = _col(tp, "osi")
    abq_s = _col(tp, "abq")
    rcv_s = _col(tp, "rcv")
    pals_s = _col(tp, "pals")
    proj_s = _col(tp, "proj_osi")
    osi_l7_s = _col(tp, "osi_l7")
    idx = {str(r["team"]).upper().strip(): r for _, r in tp.iterrows()} if tp is not None and "team" in tp.columns else {}
    # pooled series for split-based baselines
    plat_s = pd.concat([s for s in (_col(tp, "osi_vs_lhp"), _col(tp, "osi_vs_rhp")) if s is not None]) if tp is not None else None
    woba_s = pd.concat([s for s in (_col(tp, "home_woba"), _col(tp, "away_woba")) if s is not None]) if tp is not None else None
    obr_s = _col(tp, "obr")
    bhl_s = _col(tp, "bullpen_high_lev_era")
    a_plat_col = "osi_vs_lhp" if gd.home_hand == "L" else "osi_vs_rhp"   # away faces home SP hand
    h_plat_col = "osi_vs_lhp" if gd.away_hand == "L" else "osi_vs_rhp"   # home faces away SP hand

    def _mean(series, default):
        try:
            import pandas as pd
            s = pd.to_numeric(series, errors="coerce").dropna()
            return (round(float(s.mean()), 2), int(s.shape[0])) if len(s) else (default, 0)
        except Exception:
            return (default, 0)

    rows = []

    def row(cat, a_val, h_val, series, lower_better, base_default, impact, unit="", role="context"):
        ap = _emp_pctile(series, a_val, lower_better) if series is not None else None
        hp = _emp_pctile(series, h_val, lower_better) if series is not None else None
        base, n = _mean(series, base_default) if series is not None else (base_default, None)
        edge = "—"
        if ap is not None and hp is not None:
            edge = gd.away if ap > hp else (gd.home if hp > ap else "even")
        # stat-presentation standard: raw + baseline + delta + percentile + sample
        ad = (round(a_val - base, 2) if isinstance(a_val, (int, float)) and base is not None else None)
        hd = (round(h_val - base, 2) if isinstance(h_val, (int, float)) and base is not None else None)
        rows.append({"cat": cat, "a_val": a_val, "h_val": h_val, "a_pct": ap, "h_pct": hp,
                     "base": base, "a_d": ad, "h_d": hd, "n": n, "edge": edge,
                     "a_rank": _rank(ap, n), "h_rank": _rank(hp, n),
                     "impact": impact, "unit": unit, "lower_better": lower_better,
                     "role": role})

    # pitching
    row("Starting pitching (FIP)", gd.away_fip, gd.home_fip, fip_s, True, settings.LEAGUE_FIP,
        f"{(pitch_factor(gd.home_fip, gd.home_pen_factor) - pitch_factor(gd.away_fip, gd.away_pen_factor)) * anchors['league_runs']:+.2f} R",
        role="modeled")
    row("SP strikeout (K%)", gd.away_k, gd.home_k, k_s, False, 22.0, "K props · Total", "%")
    row("SP home-run risk (HR/9)", gd.away_hr9, gd.home_hr9, hr_s, True, 1.25, "Total · TT")
    # offense
    row("Offense (OSI)", gd.away_osi, gd.home_osi, osi_s, False, 50.0,
        f"{(offense_factor(gd.away_osi) - offense_factor(gd.home_osi)) * anchors['league_runs']:+.2f} R",
        role="modeled")
    row("At-bat quality (ABQ)", gd.away_context.abq, gd.home_context.abq, abq_s, False,
        50.0, "Research context")
    row("Run creation value (RCV)", gd.away_context.rcv, gd.home_context.rcv, rcv_s, False,
        50.0, "Research context")
    row("Pressure-adjusted lineup (PALS)", gd.away_context.pals, gd.home_context.pals,
        pals_s, False, 50.0, "Research context")
    row("Projected offense (projOSI)", gd.away_context.proj_osi, gd.home_context.proj_osi,
        proj_s, False, 50.0, "Research context")
    row("Recent offense (OSI L7)", gd.away_context.osi_l7, gd.home_context.osi_l7,
        osi_l7_s, False, 50.0, "Research context")
    row(f"Platoon (OSI vs {gd.home_hand}HP/{gd.away_hand}HP)", _tv(idx, gd.away, a_plat_col), _tv(idx, gd.home, h_plat_col),
        plat_s, False, 50.0, "Total · ML")
    row("Lineup quality (wOBA)", _tv(idx, gd.away, "away_woba"), _tv(idx, gd.home, "home_woba"), woba_s, False, 0.320, "Total · ML")
    row("Baserunning (OBR)", _tv(idx, gd.away, "obr"), _tv(idx, gd.home, "obr"), obr_s, False, 50.0, "ML · close games")
    # relief + environment
    row("Bullpen (factor)", gd.away_pen_factor, gd.home_pen_factor, None, True, 1.00,
        "Late ML · Total", role="modeled")
    row("Bullpen high-leverage (ERA)", _tv(idx, gd.away, "bullpen_high_lev_era"), _tv(idx, gd.home, "bullpen_high_lev_era"),
        bhl_s, True, 4.00, "Late ML · live")
    row("Park run env", gd.park_factor, gd.park_factor, None, False, 1.00,
        "Total · TT", role="modeled")
    return rows


def _signal_boost(gd, market: str, side) -> float:
    market = str(market).lower()
    if market == "total":
        return (
            signal_edge_adjustment(gd.game_signals, side="away")
            + signal_edge_adjustment(gd.game_signals, side="home")
        ) / 2
    side_key = (
        "away"
        if str(side).upper() in {gd.away, "AWAY"}
        else "home"
    )
    return signal_edge_adjustment(gd.game_signals, side=side_key)


def _market_row(market, side, line, ou, gd, probs, anchors, quote, promotion):
    probability, description = market_probability(market, side, line, gd, probs, anchors, ou)
    probability = max(0.02, min(0.98, probability))
    assessment = assess_value(
        probability,
        quote.best_odds if quote else None,
        quote.vigfree_probability if quote else None,
        promotion_status=promotion,
        signal_edge_boost=_signal_boost(gd, market, side),
    )
    tone = {
        "BET": "pos",
        "MONITOR": "warnc",
        "REVIEW": "warnc",
        "AVOID": "neg",
        "NO EDGE": "mut",
    }[assessment.action]
    return {
        "label": description,
        "market": market,
        "side": str(side),
        "line": line,
        "model": round(probability * 100, 1),
        "fair": assessment.fair_odds,
        "mkt": quote.best_odds if quote else None,
        "book": quote.best_book if quote else None,
        "impl": (
            round(quote.vigfree_probability * 100, 1)
            if quote else None
        ),
        # The book's true price with its two-sided hold removed, and the hold itself.
        # This is the "fair value" benchmark the model's edge is measured against.
        "mkt_fair": (
            prob_to_american(quote.vigfree_probability) if quote else None
        ),
        "hold": (
            round(quote.hold * 100, 1)
            if quote and quote.hold is not None else None
        ),
        "edge": (
            round(assessment.edge * 100, 1)
            if assessment.edge is not None else None
        ),
        "ev": assessment.ev_per_unit,
        "max": assessment.maximum_odds,
        "state": assessment.action,
        "tone": tone,
        "reason": assessment.reason,
        "books": quote.book_count if quote else 0,
        "market_time": quote.fetched_at if quote else None,
    }


def _norm(s):
    import re
    t = " ".join(reversed(str(s).lower().split(","))) if "," in str(s) else str(s).lower()
    return " ".join(sorted(re.sub(r"[^a-z ]", "", t).split()))


def _numf(v):
    import pandas as pd
    x = pd.to_numeric(v, errors="coerce")
    return None if pd.isna(x) else float(x)


def _extras(away, home, gd, probs, anchors, repo):
    """Start time, lineup status, SP arsenals, scenario sweep, F5 — from real pipeline data."""
    out = {"start": None, "lineup": "lineups TBD · probables confirmed",
           "arsenal_a": [], "arsenal_h": [], "scenario": [], "f5": None}
    m = repo.load("today_matchups.csv")
    if m is not None and "Away" in m.columns:
        m["Away"] = m["Away"].astype(str).str.upper().str.strip()
        m["Home"] = m["Home"].astype(str).str.upper().str.strip()
        r = m[(m["Away"] == away) & (m["Home"] == home)]
        if not r.empty:
            out["start"] = str(r.iloc[0].get("Time", "") or "")
    ln = repo.load("today_lineups.csv")
    if ln is not None and not ln.empty:
        out["lineup"] = "lineups posted"
    pm = repo.load("pitch_mix_pitcher.csv")

    def arsenal(name):
        if pm is None or "full_name" not in pm.columns:
            return []
        key = _norm(name)
        sub = pm[pm["full_name"].astype(str).map(_norm) == key]
        rows = [{"pitch": str(x.get("pitch_type", "")), "pct": _numf(x.get("pitch_pct")),
                 "whiff": _numf(x.get("whiff_rate"))} for _, x in sub.iterrows()]
        return sorted([z for z in rows if z["pct"]], key=lambda z: -z["pct"])[:6]
    out["arsenal_a"], out["arsenal_h"] = arsenal(gd.away_sp), arsenal(gd.home_sp)
    spp = repo.load("sp_profiles.csv")

    def spid(name):
        if spp is None or "pitcher_name" not in spp.columns or "pitcher_id" not in spp.columns:
            return None
        m = spp[spp["pitcher_name"].astype(str).map(_norm) == _norm(name)]
        if not m.empty:
            v = _numf(m.iloc[0]["pitcher_id"])
            return int(v) if v else None
        return None
    out["a_id"], out["h_id"] = spid(gd.away_sp), spid(gd.home_sp)
    for d in (-1.5, -1, -0.5, 0, 0.5, 1, 1.5):
        line = round((probs.exp_total + d) * 2) / 2
        po = 1 - normal_cdf((line - probs.exp_total) / anchors["total_sd"])
        out["scenario"].append((line, round(po * 100, 1)))
    f5, sdf = probs.exp_total * 0.54, anchors["total_sd"] * 0.74
    line = round(f5 * 2) / 2
    po = max(0.02, min(0.98, 1 - normal_cdf((line - f5) / sdf)))
    out["f5"] = {
        "exp": round(f5, 1),
        "line": line,
        "over": round(po * 100, 1),
        "fair": fair_price(po),
    }
    return out


def _promotion(reader):
    result = reader.get(
        "prediction_market_snapshots?market_type=eq.ml&settled=eq.true"
        "&won=not.is.null&open_prob=not.is.null"
        "&select=game_pk,snapshot_time,open_prob,delta,won,"
        "implied_probability,volume,entry_prob,signal_time"
    )
    if result.error:
        return {"verdict": "HOLD/ABSTAIN", "reasons": [result.error]}
    return promotion_verdict(result.rows)




def build_report(
    away,
    home,
    *,
    fetch=True,
    data_dir=None,
    board=None,
    reader=None,
    gate=None,
    pitcher_rows=None,
    game_number: int = 1,
):
    repo = DataRepository(data_dir)
    anchors = repo.anchors()
    gd = repo.load_game(away, home, game_number=game_number, pitcher_rows=pitcher_rows)
  # Arsenal attached inside load_game when pitcher_rows are supplied.
    repo.enrich_trends(gd, away, home)
    probs = model_probabilities(gd, anchors)
    simulation = simulate_game(
        probs,
        team_runs_sd=anchors["team_sd"],
        seed=gd.game_pk,
    )
    board = board or _live_odds(fetch=fetch)
    reader = reader or SupabaseReader()
    gate = gate or _promotion(reader)
    promotion = "PROMOTE" if gate.get("verdict") == "PROMOTE" else "HOLD/ABSTAIN"
    posted_total = board.modal_total(away, home)
    tline = posted_total if posted_total is not None else round(probs.exp_total * 2) / 2
    markets = [
        _market_row("ml", gd.home, None, None, gd, probs, anchors,
                    board.quote(away, home, "ml", gd.home), promotion),
        _market_row("ml", gd.away, None, None, gd, probs, anchors,
                    board.quote(away, home, "ml", gd.away), promotion),
        _market_row("total", "over", tline, None, gd, probs, anchors,
                    board.quote(away, home, "total", "over", tline), promotion),
        _market_row("total", "under", tline, None, gd, probs, anchors,
                    board.quote(away, home, "total", "under", tline), promotion),
    ]
    runline_team = gd.home if probs.exp_margin > 0 else gd.away
    runline = -1.5
    markets.append(
        _market_row(
            "runline", runline_team, runline, None, gd, probs, anchors,
            board.quote(away, home, "runline", runline_team, runline), promotion,
        )
    )
    ex = _extras(away, home, gd, probs, anchors, repo)
    # F5 as a first-class graded market: total over/under + ML, priced against live F5 odds
    # when present (else model fair values). Flows into the market report, decision board,
    # F5 panel, and research — all from the same rows.
    markets.extend(_f5_market_rows(gd, pitcher_rows, board, promotion, ex.get("f5")))
    conf = probs.confidence
    freshness = repo.freshness_hours("today_matchups.csv")
    return {"away": away, "home": home, "gd": gd, "probs": probs, "anchors": anchors,
            "posted_total": posted_total, "extras": ex, "movement": None, "confidence": conf,
            "markets": markets, "factors": _factors(probs),
            "advantage": _advantage(gd, anchors, repo), "simulation": simulation,
            "pitchers": pitcher_rows or [],
            "risks": risk_signals(gd), "sharp": _sharp_for(gd.game_pk, reader),
            "game_pk": gd.game_pk, "promotion": gate, "freshness_hours": freshness,
            "repo": repo, "data_dir": str(repo.data_dir),
            "model_version": settings.MODEL_VERSION, "metric_version": settings.METRIC_VERSION,
            "generated": datetime.now(timezone.utc).isoformat(timespec="seconds")}


def _sharp_for(gpk, reader):
    result = reader.get(
        "sharp_signals"
        f"?game_pk=eq.{gpk}&select=market_type,selection,divergence,steam_flag,"
        "sharp_novig_prob,soft_novig_prob,snapshot_time"
    )
    return result.rows


# ── render (Chase Analytics / Sharp Money Tracker design contract) ────────────
# Base tokens/fonts come from chase_theme.theme_css() (chase_tokens.css + chase_components.css,
# vendored from mlbma-pipeline's canonical design system). These are compatibility aliases only
# -- same values, legacy names -- so the ~150 `var(--ink)`/`var(--muted)`/etc. references below
# don't all need renaming; nothing here redefines a canonical token to a different value.
_CSS = """
:root{
  --ink: var(--text); --ink2: var(--text-2); --muted: var(--text-3); --muted-2: var(--text-4);
  --accent: var(--ca-brand); --v-deep: var(--ca-purple-dark);
}
.wrap{max-width:1180px;margin:0 auto;padding:22px 20px 70px;display:flex;flex-direction:column;gap:18px}
.num,td,th,.chip,.mval{font-variant-numeric:tabular-nums}.pos{color:var(--green)}.neg{color:var(--red)}.warnc{color:var(--gold)}.side{color:var(--side)}.mut{color:var(--muted)}
.c-elite{color:#4ADE80}.c-good{color:#7BDC5A}.c-mid{color:#FBBF24}.c-weak{color:#FB923C}.c-poor{color:#F87171}.c-na{color:var(--muted)}
/* header */
.hd{display:flex;justify-content:space-between;align-items:flex-end;gap:14px;border-bottom:1px solid var(--border);padding-bottom:14px;flex-wrap:wrap}
.hd h1{font-family:var(--display);font-weight:800;font-size:var(--mm-text-hero);letter-spacing:-.02em;margin:0;line-height:1}
.hd .sp{color:var(--ink2);font-size:var(--mm-text-base);margin-top:6px}.hd .sp b{color:var(--ink)}
.hd .meta{color:var(--muted-2);font-size:var(--mm-text-xs);text-align:right;line-height:1.5}.fresh{color:var(--green);font-weight:700}
/* logos + headshots (Chase Analytics blueprint) */
.tlogo{height:26px;width:26px;object-fit:contain;vertical-align:middle;filter:drop-shadow(0 3px 5px rgba(0,0,0,.5))}
.tlogo.lg{height:40px;width:40px}.tlogo.sm{height:18px;width:18px}
.tlf{display:inline-flex;align-items:center;justify-content:center;height:26px;width:26px;border-radius:50%;
background:var(--raised);border:1px solid var(--border-2);color:var(--ink2);font:800 var(--mm-text-2xs)/1 var(--display);vertical-align:middle}
.tlf.lg{height:40px;width:40px;font-size:var(--mm-text-sm)}.tlf.sm{height:18px;width:18px;font-size:var(--mm-text-2xs)}
.teams{display:flex;align-items:center;gap:11px}
.pitchers{display:flex;align-items:center;gap:14px;margin:11px 0 4px;flex-wrap:wrap}
.pcell{display:flex;align-items:center;gap:9px}
.phead{width:42px;height:42px;border-radius:50%;object-fit:cover;object-position:center top;background:var(--raised);
border:2px solid #454B61;box-shadow:0 5px 14px rgba(0,0,0,.45),0 0 0 2px rgba(154,107,255,.12)}
.phead-na{background:linear-gradient(160deg,var(--raised),var(--card))}.phead-na::after{content:"";display:block}
.pmeta{line-height:1.3}.pmeta b{color:var(--ink);font-size:var(--mm-text-md)}.pmeta span{display:block;color:var(--muted);font-size:var(--mm-text-xs)}
.vsx{color:var(--muted-2);font:700 var(--mm-text-xs) var(--display);text-transform:uppercase}
/* strip chips */
.strip{display:grid;grid-template-columns:repeat(8,1fr);gap:9px}
@media(max-width:880px){.strip{grid-template-columns:repeat(4,1fr)}}
.chipc{background:var(--raised);border:1px solid var(--border);border-radius:8px;padding:9px 10px;text-align:center}
.chipc .k{color:var(--muted);font-size:var(--mm-text-2xs);text-transform:uppercase;letter-spacing:.06em;font-weight:800}
.chipc .v{color:var(--ink);font-family:var(--display);font-weight:800;font-size:var(--mm-text-2xl);margin-top:3px}
.vbar{display:flex;align-items:center;gap:14px;padding:11px 16px;border-radius:8px;border:1px solid var(--border-2);font-size:var(--mm-text-base);background:var(--card)}
.vbar b{font-family:var(--display);font-weight:800;font-size:var(--mm-text-lg);letter-spacing:.03em}.vbar span{color:var(--ink2)}
.vbar.pos{border-color:rgba(60,203,127,.3);background:rgba(60,203,127,.10)}.vbar.pos b{color:#7BDC5A}
.vbar.warnc{border-color:rgba(232,194,74,.3);background:rgba(232,194,74,.10)}.vbar.warnc b{color:var(--gold)}
.vbar.neg{border-color:rgba(242,84,91,.3);background:rgba(242,84,91,.10)}.vbar.neg b{color:#FCA5A5}
.vbar.mut b{color:var(--muted)}
.cols{display:grid;grid-template-columns:1fr 1fr;gap:14px;align-items:start;margin-top:14px}@media(max-width:760px){.cols{grid-template-columns:1fr}}
.note{color:var(--muted);font-size:var(--mm-text-xs);margin-top:8px}
.rtabs{margin-top:20px}
.rtabbar{display:flex;gap:2px;border-bottom:1px solid var(--border);flex-wrap:wrap;margin-bottom:14px}
.rtabbar button{padding:9px 16px;font:700 var(--mm-text-base) var(--sans);color:var(--muted);cursor:pointer;border:0;border-bottom:2.5px solid transparent;margin-bottom:-1px;background:none}
.rtabbar button:hover{color:var(--ink2)}.rtabbar button.on{color:var(--ink);border-bottom-color:var(--accent)}.pn{display:none}.pn.on{display:block}
th[title],td[title]{cursor:help;text-decoration:underline dotted rgba(148,163,184,.4);text-underline-offset:3px}
/* section boards — MLBMA .ca-board from design system; local typography */
.ca-board h2,.sec h2,.ca-board .ca-section-head .title,.sec .ca-section-head .title{
font-family:var(--display);font-weight:800;font-size:var(--mm-text-base);letter-spacing:.06em;text-transform:uppercase;color:var(--v-light);margin:0 0 10px}
.ca-board>.ca-section-head,.sec>.ca-section-head{margin:-4px 0 12px}
.ca-board>.body,.sec>.body{padding:0}
.ca-board+.ca-board,.sec+.sec{margin-top:14px}
.table-scroll{width:100%;overflow-x:auto}
/* tables */
table{width:100%;border-collapse:collapse}
th{color:var(--ink2);font-size:var(--mm-text-xs);letter-spacing:.05em;text-transform:uppercase;font-weight:800;text-align:right;padding:9px 12px;border-bottom:1px solid var(--border-2);white-space:nowrap}
th:first-child{text-align:left}
td{padding:9px 12px;text-align:right;border-bottom:1px solid rgba(255,255,255,.06);font-size:var(--mm-text-md)}
td:first-child{text-align:left;font-weight:600}tbody tr:last-child td{border-bottom:none}tbody tr:hover td{background:rgba(124,77,255,.08)}
.chip{font-family:var(--display);font-weight:800}
.pill{display:inline-block;padding:3px 10px;border-radius:999px;font-size:var(--mm-text-2xs);font-weight:800;letter-spacing:.04em;border:1px solid transparent}
.pill.pos{background:rgba(60,203,127,.13);color:#7BDC5A;border-color:rgba(60,203,127,.22)}
.pill.warnc{background:rgba(232,194,74,.12);color:var(--gold);border-color:rgba(232,194,74,.22)}
.pill.neg{background:rgba(242,84,91,.12);color:#FCA5A5;border-color:rgba(242,84,91,.22)}
.pill.mut{background:rgba(255,255,255,.06);color:var(--ink2)}
/* comparison + driver bars */
.dbar{display:inline-block;width:64px;height:7px;border-radius:4px;background:rgba(255,255,255,.07);vertical-align:middle;overflow:hidden}
.dbar i{display:block;height:100%;border-radius:4px}
.delta{font-size:var(--mm-text-xs);font-weight:700}.n{color:var(--muted-2);font-size:var(--mm-text-2xs);font-weight:600}
/* market-vs-model bars */
.mmwrap{display:flex;flex-direction:column;gap:7px}.mm{display:flex;align-items:center;gap:9px}
.mml{flex:0 0 96px;font-size:var(--mm-text-sm);color:var(--ink2)}.mmbar{position:relative;flex:1;height:12px;background:rgba(255,255,255,.06);border-radius:4px}
.mmbar i.mod{position:absolute;left:0;top:0;height:100%;background:var(--teal);border-radius:4px;opacity:.55}
.mmbar i.imp{position:absolute;top:-2px;width:2px;height:16px;background:#fff}.mmv{flex:0 0 46px;text-align:right;font-weight:700;font-size:var(--mm-text-sm)}
/* arsenal */
.arshd{font-size:var(--mm-text-xs);color:var(--ink2);font-weight:700;margin:2px 0 6px}.ars{display:flex;flex-direction:column;gap:5px}
.arl{display:flex;align-items:center;gap:8px;font-size:var(--mm-text-xs)}.apt{flex:0 0 34px;color:var(--muted);font-weight:700}
.abar{flex:1;height:8px;background:rgba(255,255,255,.06);border-radius:3px;overflow:hidden}.abar i{display:block;height:100%;background:var(--accent);border-radius:3px}
.apv{flex:0 0 32px;text-align:right;font-weight:700}.aw{flex:0 0 50px;text-align:right;color:var(--muted-2);font-size:var(--mm-text-2xs)}
.mvrow{display:flex;align-items:center;gap:9px;font-size:var(--mm-text-base)}.mvrow b{font-family:var(--display)}.mvarrow{color:var(--muted)}
.advbar{display:flex;align-items:center;gap:8px;justify-content:flex-end}
.advbar .seg{height:8px;border-radius:3px}.advbar .a{background:#9A6BFF}.advbar .h{background:#2dd4bf}
/* charts */
.charts{display:grid;grid-template-columns:1fr 1fr;gap:14px}@media(max-width:880px){.charts{grid-template-columns:1fr}}
.cap{display:flex;justify-content:space-between;font-size:var(--mm-text-xs);font-weight:700;margin-top:3px}
/* drawer */
details{border-top:1px solid var(--border);padding:12px 16px}summary{cursor:pointer;color:var(--ink2);font-weight:700;font-size:var(--mm-text-base);list-style:none}
summary::before{content:"▸ ";color:var(--accent)}details[open] summary::before{content:"▾ "}
details ul{margin:8px 0 0;padding-left:18px}details li{font-size:var(--mm-text-sm);color:var(--muted);margin:4px 0}
/* decision-first matchup */
.matchup-banner{position:relative;margin:0 0 12px;padding:18px 20px 14px;border-radius:16px;overflow:hidden;
background:linear-gradient(180deg,rgba(255,255,255,.06),transparent 28%),linear-gradient(180deg,var(--ca-board-top,#181B26),var(--ca-board-bottom,#12141D));
border:2px solid var(--ca-panel-border,var(--border-violet));box-shadow:var(--ca-card-shadow),inset 0 1px 0 rgba(255,255,255,.08)}
.matchup-banner::before{content:"";position:absolute;inset:0 0 auto 0;height:2px;background:var(--v-grad);opacity:.85}
.matchup-banner__teams{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:14px}
.matchup-banner__team{display:flex;align-items:center;gap:12px;min-width:0}
.matchup-banner__team--home{justify-content:flex-end;text-align:right}
.matchup-banner__team-copy{display:flex;flex-direction:column;gap:2px;min-width:0}
.matchup-banner__abbr{font:800 var(--mm-text-display) var(--display);letter-spacing:-.02em;line-height:1;color:var(--ink)}
.matchup-banner__team--favored .matchup-banner__abbr{color:var(--teal)}
.matchup-banner__osi-tag{font-size:var(--mm-text-xs);font-weight:700;margin-top:1px}
.matchup-banner__center{text-align:center;padding:0 8px}
.matchup-banner__label{display:block;color:var(--muted);font-size:var(--mm-text-2xs);font-weight:800;letter-spacing:.1em;text-transform:uppercase}
.matchup-banner__score{display:flex;align-items:baseline;justify-content:center;gap:8px;margin:4px 0 6px}
.matchup-banner__runs{font:800 var(--mm-text-hero) var(--display);letter-spacing:-.03em;line-height:1;color:var(--ink)}
.matchup-banner__dash{color:var(--muted-2);font:800 var(--mm-text-2xl) var(--display)}
.matchup-banner__meta{display:flex;align-items:center;justify-content:center;gap:8px;flex-wrap:wrap;font-size:var(--mm-text-xs);color:var(--ink2)}
.matchup-banner__lean b{font-family:var(--display)}
.matchup-banner__osi-bar{display:flex;height:5px;border-radius:999px;overflow:hidden;margin:12px 0 14px;background:rgba(255,255,255,.06)}
.matchup-banner__osi-seg--away{background:linear-gradient(90deg,#9A6BFF,#7C4DFF)}
.matchup-banner__osi-seg--home{background:linear-gradient(90deg,#2dd4bf,#14b8a6)}
.matchup-banner__pitchers{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:12px}
.matchup-banner__sp{display:flex;align-items:center;gap:10px;min-width:0}
.matchup-banner__sp--home{justify-content:flex-end;text-align:right}
.matchup-banner__sp .phead{width:48px;height:48px;border-width:2px}
.matchup-banner__sp b{display:block;font:800 var(--mm-text-md) var(--display);color:var(--ink);margin-top:1px}
.matchup-banner__sp .mut{display:block;font-size:var(--mm-text-2xs);text-transform:uppercase;letter-spacing:.07em;font-weight:800}
.matchup-banner__sp-stats{display:flex;align-items:center;gap:6px;flex-wrap:wrap;margin-top:4px;justify-content:flex-start}
.matchup-banner__sp--home .matchup-banner__sp-stats{justify-content:flex-end}
.matchup-banner__vs{font:800 var(--mm-text-xs) var(--display);color:var(--muted-2);letter-spacing:.12em}
.hand-pill{display:inline-block;padding:2px 7px;border-radius:999px;font-size:var(--mm-text-2xs);font-weight:800;letter-spacing:.04em;border:1px solid transparent;vertical-align:middle}
.hand-pill.hand-l{color:#93C5FD;border-color:rgba(147,197,253,.35);background:rgba(147,197,253,.1)}
.hand-pill.hand-r{color:#FCA5A5;border-color:rgba(252,165,165,.35);background:rgba(252,165,165,.1)}
.matchup-banner__kickoff{margin-top:12px;padding-top:10px;border-top:1px solid var(--border-2);text-align:center;font-size:var(--mm-text-xs);color:var(--muted);font-weight:700;letter-spacing:.04em}
.matchup-banner--compact{padding:14px 16px 12px;margin-bottom:10px}
.matchup-banner--compact .matchup-banner__abbr{font-size:var(--mm-text-2xl)}
.matchup-banner--compact .matchup-banner__runs{font-size:var(--mm-text-3xl)}
.matchup-banner--compact .matchup-banner__pitchers{display:none}
.matchup-banner--compact .matchup-banner__osi-bar{margin-bottom:0}
.matchup-verdict{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin:0 0 10px}
.matchup-verdict__pick b{font-family:var(--display);font-size:var(--mm-text-md)}
.matchup-verdict__stats{display:flex;align-items:center;gap:10px;flex-wrap:wrap;font-size:var(--mm-text-sm);color:var(--ink2)}
.matchup-kpi-strip{display:grid;grid-template-columns:repeat(6,1fr);gap:1px;background:var(--border);border:1.5px solid var(--border-2);border-radius:12px;overflow:hidden;margin:0 0 10px}
.matchup-kpi{background:linear-gradient(180deg,var(--raised),var(--card));padding:11px 12px;text-align:center}
.matchup-kpi .k{display:block;color:var(--muted);font-size:var(--mm-text-2xs);text-transform:uppercase;letter-spacing:.07em;font-weight:800;margin-bottom:5px}
.matchup-kpi .v{font-family:var(--display);font-weight:800;font-size:var(--mm-text-lg);line-height:1.1}
.matchup-meta-bar{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:12px}
.matchup-meta-bar span{flex:1 1 180px;background:linear-gradient(180deg,rgba(255,255,255,.04),transparent),var(--card);
border:1px solid var(--border-2);border-radius:10px;padding:9px 11px;color:var(--ink2);font-size:var(--mm-text-xs);line-height:1.35}
.matchup-meta-bar b{display:block;color:var(--muted);font-size:var(--mm-text-2xs);text-transform:uppercase;letter-spacing:.06em;margin-bottom:3px;font-weight:800}
.matchup-head{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:18px;padding:4px 0 14px;border-bottom:1px solid var(--border)}
.matchup-team{display:flex;align-items:center;gap:10px}.matchup-team.home{justify-content:flex-end;text-align:right}
.matchup-team b{display:block;font:800 var(--mm-text-display) var(--display)}.matchup-team span{display:block;color:var(--muted);font-size:var(--mm-text-sm);margin-top:2px}
.score-projection{text-align:center}.score-projection span,.score-projection i{display:block;color:var(--muted);font-size:var(--mm-text-2xs);font-style:normal;text-transform:uppercase}
.score-projection b{display:block;font:800 var(--mm-text-3xl) var(--display);margin:3px 0}
.decision-strip{display:grid;grid-template-columns:repeat(6,1fr);border:1px solid var(--border-2);border-radius:8px;margin:10px 0;overflow:hidden}
.decision-strip span{padding:10px 12px;border-right:1px solid var(--border);color:var(--muted);font-size:var(--mm-text-2xs);text-transform:uppercase}
.decision-strip span:last-child{border-right:0}.decision-strip b{display:block;color:var(--ink);font:800 var(--mm-text-xl) var(--display);text-transform:none;margin-bottom:2px}
.availability{display:flex;gap:1px;background:var(--border);border:1px solid var(--border);border-radius:8px;overflow:hidden;margin-bottom:12px}
.availability span{flex:1;background:var(--card);padding:9px 11px;color:var(--ink2);font-size:var(--mm-text-xs)}
.availability b{display:block;color:var(--muted);font-size:var(--mm-text-2xs);text-transform:uppercase;margin-bottom:2px}.availability i{font-style:normal;font-weight:800}
.decision-grid{display:grid;grid-template-columns:1.45fr 1fr;gap:12px;margin:12px 0}.missing-row{display:flex;align-items:center;gap:6px;flex-wrap:wrap;margin-top:10px}
.missing-row>b{color:var(--muted);font-size:var(--mm-text-2xs);text-transform:uppercase;margin-right:3px}
.pitcher-grid{display:grid;grid-template-columns:1fr;gap:12px;margin:12px 0}
.pitch-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:var(--border);border:1px solid var(--border);border-radius:6px;overflow:hidden;margin-bottom:9px}
.pitch-summary span{background:var(--raised);padding:8px;color:var(--muted);font-size:var(--mm-text-2xs);text-transform:uppercase}
.pitch-summary b,.pitch-summary em{display:block;color:var(--ink);font:800 var(--mm-text-xl) var(--display);font-style:normal}
.pitch-summary i{display:block;color:var(--muted);font-size:var(--mm-text-2xs);font-style:normal;text-transform:none}
.pitch-source{color:var(--muted);font-size:var(--mm-text-2xs);margin-bottom:7px}.model-details{border:1px solid var(--border);border-radius:8px;margin-top:12px}
.pitch-name-meta{display:block;font-size:var(--mm-text-2xs);margin-top:2px}
.model-details p{color:var(--muted);font-size:var(--mm-text-sm);line-height:1.5;max-width:1000px}
@media(max-width:980px){.matchup-kpi-strip{grid-template-columns:repeat(3,1fr)}.decision-grid,.pitcher-grid{grid-template-columns:1fr}}
@media(max-width:680px){.matchup-banner__teams{grid-template-columns:1fr;gap:10px}.matchup-banner__center{order:-1}
.matchup-banner__team--home{justify-content:flex-start;text-align:left}.matchup-banner__abbr{font-size:var(--mm-text-2xl)}
.matchup-banner__runs{font-size:var(--mm-text-display)}.matchup-banner__pitchers{grid-template-columns:1fr;gap:8px}
.matchup-banner__sp--home{justify-content:flex-start;text-align:left}.matchup-banner__vs{display:none}
.matchup-kpi-strip{grid-template-columns:repeat(2,1fr)}.matchup-meta-bar span{flex:1 1 100%}.pitch-summary{grid-template-columns:repeat(2,1fr)}}
"""


_ACTION_TONE = {"BET": "pos", "MONITOR": "warnc", "REVIEW": "warnc", "AVOID": "neg", "NO EDGE": "mut"}


def _priced_row(market, side, line, model_prob, quote, promotion, label):
    """Build a graded market row (same shape as ``_market_row``) from a model probability and
    a board quote — used for markets like F5 that don't go through ``market_probability``."""
    model_prob = max(0.02, min(0.98, model_prob))
    assessment = assess_value(
        model_prob,
        quote.best_odds if quote else None,
        quote.vigfree_probability if quote else None,
        promotion_status=promotion,
    )
    return {
        "label": label, "market": market, "side": str(side), "line": line,
        "model": round(model_prob * 100, 1), "fair": assessment.fair_odds,
        "mkt": quote.best_odds if quote else None,
        "book": quote.best_book if quote else None,
        "impl": round(quote.vigfree_probability * 100, 1) if quote else None,
        "mkt_fair": prob_to_american(quote.vigfree_probability) if quote else None,
        "hold": round(quote.hold * 100, 1) if quote and quote.hold is not None else None,
        "edge": round(assessment.edge * 100, 1) if assessment.edge is not None else None,
        "ev": assessment.ev_per_unit, "max": assessment.maximum_odds,
        "state": assessment.action, "tone": _ACTION_TONE[assessment.action],
        "reason": assessment.reason, "books": quote.book_count if quote else 0,
        "market_time": quote.fetched_at if quote else None,
    }


def _f5_projection(pitcher_rows, away, home):
    """First-5 projection from the two starters' simulated F5 ER distributions, or None.

    Each starter's F5 ER is the runs the OPPOSING lineup scores in innings 1-5, so the F5
    total is the sum of both and the F5 lead falls to whichever starter allows fewer.
    """
    def f5_for(team):
        for row in (pitcher_rows or []):
            if str(row.get("team") or "").upper() == team:
                dist = (row.get("projections") or {}).get("F5_ER")
                if dist and dist.get("sd"):
                    return row, dist
        return None, None

    away_sp, away_f5 = f5_for(away)   # away starter -> runs the HOME team scores in F5
    home_sp, home_f5 = f5_for(home)   # home starter -> runs the AWAY team scores in F5
    if not (away_f5 and home_f5):
        return None
    home_runs_mean, away_runs_mean = away_f5["mean"], home_f5["mean"]
    total_mean = home_runs_mean + away_runs_mean
    total_sd = max(0.5, math.sqrt(away_f5["sd"] ** 2 + home_f5["sd"] ** 2))
    diff_mean = away_runs_mean - home_runs_mean
    diff_sd = max(0.5, math.sqrt(away_f5["sd"] ** 2 + home_f5["sd"] ** 2))
    p_away_lead = max(0.02, min(0.98, 1 - normal_cdf((0 - diff_mean) / diff_sd)))
    return {
        "total_mean": total_mean, "total_sd": total_sd, "p_away_lead": p_away_lead,
        "away_sp": away_sp, "home_sp": home_sp, "away_f5": away_f5, "home_f5": home_f5,
    }


def _f5_market_rows(gd, pitcher_rows, board, promotion, fallback_f5):
    """Graded F5 market rows (total over/under + ML), priced against live F5 odds when present.

    Prices at the book's posted F5 line when available so the quote actually matches; otherwise
    the model line. Falls back to a single model-only row when no starter F5 sim exists.
    """
    proj = _f5_projection(pitcher_rows, gd.away, gd.home)
    if proj is None:
        f5 = fallback_f5
        if not f5:
            return []
        return [{"label": f"F5 Total Over {f5['line']:g} (≈)", "market": "f5_total",
                 "side": "over", "line": f5["line"], "model": f5["over"], "fair": f5["fair"],
                 "mkt": None, "impl": None, "mkt_fair": None, "hold": None, "edge": None,
                 "ev": None, "max": f5["fair"], "state": "NO EDGE", "tone": "mut",
                 "reason": "No starter F5 sim", "book": None, "books": 0, "market_time": None}]
    total_mean, total_sd = proj["total_mean"], proj["total_sd"]
    posted = [q.line for q in board.game_quotes(gd.away, gd.home)
              if q.market == "f5_total" and q.line is not None]
    line = max(set(posted), key=posted.count) if posted else round(total_mean * 2) / 2
    p_over = max(0.02, min(0.98, 1 - normal_cdf((line - total_mean) / total_sd)))
    p_away = proj["p_away_lead"]
    lead_team = gd.away if p_away >= 0.5 else gd.home
    lead_p = p_away if p_away >= 0.5 else (1 - p_away)
    return [
        _priced_row("f5_total", "over", line, p_over,
                    board.quote(gd.away, gd.home, "f5_total", "over", line), promotion,
                    f"F5 Total Over {line:g}"),
        _priced_row("f5_total", "under", line, 1 - p_over,
                    board.quote(gd.away, gd.home, "f5_total", "under", line), promotion,
                    f"F5 Total Under {line:g}"),
        _priced_row("f5_ml", lead_team, None, lead_p,
                    board.quote(gd.away, gd.home, "f5_ml", lead_team), promotion,
                    f"F5 ML {lead_team}"),
    ]


def _graded_market_row(market, esc):
    """One graded market line — shared by full-game and F5 tables."""
    market_price = f'{market["mkt"]:+d}' if market.get("mkt") is not None else "—"
    novig_fair = market.get("mkt_fair")
    hold = market.get("hold")
    if novig_fair is not None:
        hold_tag = (
            f'<span class="mut hold-tag"> {hold:.1f}% hold</span>'
            if hold is not None else ""
        )
        novig_cell = f'{novig_fair:+d}{hold_tag}'
    else:
        novig_cell = '<span class=mut>—</span>'
    edge_cls = edge_grade((market.get("edge") or 0) / 100) if market.get("edge") is not None else "c-na"
    edge = (
        f'<b class="{edge_cls}">{market["edge"]:+.1f}pt</b>'
        if market.get("edge") is not None else '<span class="c-na">—</span>'
    )
    ev_cls = edge_grade((market.get("ev") or 0)) if market.get("ev") is not None else "c-na"
    ev = (
        f'<b class="{ev_cls}">{market["ev"] * 100:+.1f}%</b>'
        if market.get("ev") is not None else '<span class="c-na">—</span>'
    )
    model_cell = pct_chip_html(market.get("model"), digits=1) if market.get("model") is not None else "—"
    return (
        f'<tr><td><b>{esc(market["label"])}</b></td><td>{market_price}</td>'
        f'<td>{novig_cell}</td><td>{market["fair"]:+d}</td>'
        f'<td class=num>{model_cell}</td><td class=num>{edge}</td>'
        f'<td class=num>{ev}</td><td><span class="pill {market["tone"]}">'
        f'{esc(market["state"])}</span></td></tr>'
    )


def _weather_detail(weather) -> str:
    if weather.get("status") == "dome":
        return "Dome · neutral run environment"
    temperature = weather.get("temp_f")
    if temperature is None:
        temperature = weather.get("temperature_f")
    wind_out = weather.get("wind_out_mph")
    rain = weather.get("precipitation_probability_pct")
    wx_runs = (weather_run_factor(weather) - 1.0) * 100
    wx_tag = f' · modeled runs {wx_runs:+.1f}%' if abs(wx_runs) >= 0.1 else ' · neutral'
    if temperature is None:
        return "Weather unavailable"
    return (
        f'{temperature:.0f}°F · wind {"out" if (wind_out or 0) >= 0 else "in"} '
        f'{abs(wind_out or 0):.0f} mph · rain {rain or 0:.0f}%{wx_tag}'
    )


def _adv_metric_context(cat: str) -> str:
    low = cat.lower()
    if "fip" in low:
        return "fip"
    if "strikeout" in low or "k%" in low:
        return "kpct"
    if "home-run" in low or "hr/9" in low:
        return "hr9"
    if "woba" in low:
        return "woba"
    if "obr" in low or "baserunning" in low:
        return "obr"
    if "abq" in low:
        return "abq"
    if "rcv" in low:
        return "rcv"
    if "pals" in low:
        return "pals"
    if "projosi" in low.replace(" ", ""):
        return "projosi"
    if "bullpen (factor)" in low:
        return "park"
    if "era" in low:
        return "era"
    if "park" in low:
        return "park"
    return "osi"


def _adv_val_cell(val, cat: str, unit: str) -> str:
    if not isinstance(val, (int, float)):
        return "—"
    ctx = _adv_metric_context(cat)
    digits = 3 if ctx == "woba" else (1 if unit == "%" else 2)
    return val_grade_html(val, ctx, digits=digits, suffix=unit, bold=True)


def _fmt_optional(value, *, digits=1, suffix=""):
    if value is None:
        return "—"
    if isinstance(value, float):
        return f'{value:.{digits}f}{suffix}'
    return f'{value}{suffix}'


def _workload_context_rows(gd, travel, esc):
    away_starter = gd.away_starter_features
    home_starter = gd.home_starter_features
    away_pen = gd.away_bullpen_features
    home_pen = gd.home_bullpen_features
    away_line = gd.away_lineup_features
    home_line = gd.home_lineup_features
    away_travel = travel.get("away") or {}
    home_travel = travel.get("home") or {}
    away_injury = gd.away_injury_features
    home_injury = gd.home_injury_features

    def line_value(value):
        if value.get("status") not in {"confirmed", "projected"}:
            return "Not posted"
        return (
            f'{value.get("projected_osi", "—")} vs '
            f'{value.get("team_baseline_osi", "—")} baseline · '
            f'{value.get("matched_batters", 0)}/9 matched'
        )

    def travel_value(value):
        if value.get("status") != "available":
            return "No recent game"
        return (
            f'{value.get("rest_hours", 0):.1f}h rest · '
            f'{value.get("travel_miles", 0):.0f} mi'
        )

    def injury_value(value):
        players = value.get("impact_players") or []
        if not players:
            return "No quantified hitter loss"
        return ", ".join(player["player"] for player in players[:3])

    rows = [
        (
            "Starter expected level",
            f'{away_starter.get("skill_fip", settings.LEAGUE_FIP):.2f} runs/9 scale',
            f'{home_starter.get("skill_fip", settings.LEAGUE_FIP):.2f} runs/9 scale',
            "Lower is better",
        ),
        (
            "Starter workload",
            f'{away_starter.get("expected_ip", 5.2):.1f} projected innings',
            f'{home_starter.get("expected_ip", 5.2):.1f} projected innings',
            "Shapes bullpen exposure and outs props",
        ),
        (
            "Bullpen quality",
            f'{away_pen.get("skill_fip", settings.LEAGUE_BULLPEN_ERA):.2f} skill · '
            f'{away_pen.get("pitches_1d") or 0:.0f} pitches yesterday · '
            f'{away_pen.get("pitches_2d") or 0:.0f} in 2d',
            f'{home_pen.get("skill_fip", settings.LEAGUE_BULLPEN_ERA):.2f} skill · '
            f'{home_pen.get("pitches_1d") or 0:.0f} pitches yesterday · '
            f'{home_pen.get("pitches_2d") or 0:.0f} in 2d',
            "Lower quality and fresher workload favor the offense",
        ),
        (
            "Lineup vs starter hand",
            line_value(away_line),
            line_value(home_line),
            f'{esc(gd.away)} vs {esc(gd.home_hand)}HP · {esc(gd.home)} vs {esc(gd.away_hand)}HP',
        ),
        (
            "Unavailable hitters",
            injury_value(away_injury),
            injury_value(home_injury),
            "Quantified before confirmed lineups",
        ),
        (
            "Rest and travel",
            travel_value(away_travel),
            travel_value(home_travel),
            "Short rest, distance, timezone",
        ),
    ]
    return "".join(
        f'<tr><td><b>{esc(label)}</b></td><td>{esc(away_value)}</td>'
        f'<td>{esc(home_value)}</td><td class=mut>{context_note}</td></tr>'
        for label, away_value, home_value, context_note in rows
    )


def _matchup_context_panel(gd, probability, context, esc):
    """Environment, splits, and workload — always visible before market boards."""
    weather = context.get("weather") or {}
    lineups = context.get("lineups") or {}
    umpire = context.get("umpire") or {}
    travel = context.get("travel") or {}
    away_lineup = (lineups.get("away") or {}).get("status", "unavailable")
    home_lineup = (lineups.get("home") or {}).get("status", "unavailable")
    umpire_label = (
        umpire.get("umpire")
        if umpire.get("status") == "announced"
        else "Not announced"
    )
    park_pct = (gd.park_factor - 1.0) * 100
    park_cell = val_grade_html(gd.park_factor, "park", digits=3)

    def split_row(team, ctx, opposing_hand, arsenal):
        platoon = ctx.platoon_osi
        woba = ctx.woba
        arsenal_note = ""
        if arsenal.get("er_factor") is not None:
            arsenal_note = (
                f' · pitch-mix {pitch_mix_runs_chip(arsenal.get("er_factor"))}'
                f' <span class=mut>({arsenal.get("batters_matched", 0)} batters)</span>'
            )
        return (
            f'<tr><td><b>{esc(team)}</b><span class=mut> vs {esc(opposing_hand)}HP</span></td>'
            f'<td>{val_chip_html(platoon, "osi", digits=0) if platoon is not None else "<span class=c-na>—</span>"}</td>'
            f'<td>{val_chip_html(woba, "woba", digits=3) if woba is not None else "<span class=c-na>—</span>"}</td>'
            f'<td>{val_chip_html(ctx.osi, "osi", digits=0) if ctx.osi is not None else "<span class=c-na>—</span>"}</td>'
            f'<td class=mut>{esc(str(ctx.window_direction or "—"))}{arsenal_note}</td></tr>'
        )

    splits_rows = (
        split_row(gd.away, gd.away_context, gd.home_hand, gd.away_arsenal_features)
        + split_row(gd.home, gd.home_context, gd.away_hand, gd.home_arsenal_features)
    )
    workload_rows = _workload_context_rows(gd, travel, esc)
    env_bits = [
        f'<span><b>Park</b>{park_cell} <span class=mut>({park_pct:+.1f}% runs)</span></span>',
        f'<span><b>Weather</b>{esc(_weather_detail(weather))}</span>',
        f'<span><b>Plate umpire</b>{esc(str(umpire_label))}</span>',
        f'<span><b>Lineups</b>{esc(gd.away)} {esc(away_lineup)} · {esc(gd.home)} {esc(home_lineup)}</span>',
        f'<span><b>SP hands</b>{esc(gd.away_sp)} ({esc(gd.away_hand)}HP) · {esc(gd.home_sp)} ({esc(gd.home_hand)}HP)</span>',
        f'<span><b>Coverage</b>{probability.data_coverage_pct}%</span>',
    ]
    return f"""<div class=ca-board>{section_head("Matchup context", icon="matchups")}<div class=body>
      <div class=matchup-env-strip>{"".join(env_bits)}</div>
      <div class=matchup-context-grid>
        <div><div class=ca-subhead>Splits &amp; handedness</div>
          <div class=table-scroll><table><tr><th>Team</th><th>Platoon OSI</th><th>wOBA</th><th>OSI</th><th>Trend · pitch-mix runs</th></tr>{splits_rows}</table></div>
        </div>
        <div><div class=ca-subhead>Bullpen, workload &amp; inputs</div>
          <div class=table-scroll><table><tr><th>Input</th><th>{esc(gd.away)}</th><th>{esc(gd.home)}</th><th>Meaning</th></tr>{workload_rows}</table></div>
        </div>
      </div>
    </div></div>"""


def _f5_panel(r, gd, esc):
    """First-5-innings panel — congruent with the market report: same graded F5 rows, shown
    with the live price + edge when F5 odds are available, model fair value otherwise."""
    proj = _f5_projection(r.get("pitchers"), gd.away, gd.home)
    f5_rows = [m for m in r.get("markets", []) if str(m.get("market") or "").startswith("f5_")]
    if not f5_rows:
        return ""
    total_over = next((m for m in f5_rows if m["market"] == "f5_total" and m["side"] == "over"), None)
    ml = next((m for m in f5_rows if m["market"] == "f5_ml"), None)

    def quote_bit(m, lean_label):
        """One F5 line: the model lean, then the live price+edge (graded) or the model fair."""
        if isinstance(m.get("mkt"), int):
            edge = (f' <b class={m.get("tone", "mut")}>{m["edge"]:+.1f}pt</b>'
                    if m.get("edge") is not None else "")
            tail = (f'<span class=mut> live {m["mkt"]:+d}'
                    + (f' ({esc(str(m.get("book")))})' if m.get("book") else "") + '</span>'
                    + edge + f' <span class="pill {m["tone"]}">{esc(m["state"])}</span>')
        else:
            tail = f'<span class=mut> fair {m["fair"]:+d}</span>'
        return f'<span><b>{esc(lean_label)}</b>{m["model"]:.0f}%{tail}</span>'

    parts = []
    if total_over is not None:
        lean = "over" if total_over["model"] >= 50 else "under"
        # show the side the model leans
        side_row = total_over if lean == "over" else next(
            (m for m in f5_rows if m["market"] == "f5_total" and m["side"] == "under"), total_over)
        parts.append(quote_bit(side_row, f'F5 Total {side_row["line"]:g} {lean}'))
    if ml is not None:
        parts.append(quote_bit(ml, f'F5 ML {esc(ml["side"])}'))

    sp_html = ""
    if proj is not None:
        def sp_cell(sp, dist, team):
            name = esc((sp or {}).get("pitcher") or team)
            return (f'<span><b>{esc(team)} SP · {name}</b>{dist["mean"]:.2f} ER F5 '
                    f'<span class=mut>({dist["p10"]:.0f}–{dist["p90"]:.0f})</span></span>')
        sp_html = (f'<div class=availability>{sp_cell(proj["away_sp"], proj["away_f5"], gd.away)}'
                   f'{sp_cell(proj["home_sp"], proj["home_f5"], gd.home)}</div>')
    f5_table = "".join(_graded_market_row(market, esc) for market in f5_rows)
    table_html = (
        f'<div class="table-scroll table-scroll--spaced"><table><tr><th>Bet</th><th>Best</th>'
        f'<th>No-vig fair</th><th>Model fair</th><th>Model%</th><th>Edge</th><th>EV</th><th>State</th></tr>'
        f'{f5_table}</table></div>'
        if f5_table else ""
    )
    return (f'<div class=ca-board>{section_head("First 5 innings (F5)", icon="markets")}<div class=body>'
            f'<div class=availability>{"".join(parts)}</div>{sp_html}{table_html}</div></div>')


def _hand_pill(hand: str) -> str:
    h = str(hand or "R").upper()[:1]
    cls = "hand-l" if h == "L" else "hand-r"
    return f'<span class="hand-pill {cls}">{html.escape(h)}HP</span>'


def _sp_stat_chips(gd, side: str) -> str:
    """Compact graded SP inputs for the banner."""
    if side == "away":
        k, fip = gd.away_k, gd.away_fip
    else:
        k, fip = gd.home_k, gd.home_fip
    parts = []
    if k is not None:
        parts.append(val_chip_html(k, "kpct", digits=1, suffix="% K"))
    if fip is not None:
        parts.append(val_chip_html(fip, "fip", digits=2, suffix=" FIP"))
    return "".join(parts)


def _matchup_banner(r: dict, esc, *, compact: bool = False) -> str:
    """Broadcast-style matchup hero — teams, score, OSI bar, starter row."""
    gd, prob = r["gd"], r["probs"]
    ex = r.get("extras") or {}
    favored = gd.home if prob.exp_margin > 0 else gd.away
    lean_margin = abs(prob.exp_margin)
    away_id, home_id = ex.get("a_id"), ex.get("h_id")
    start = str(ex.get("start") or gd.start_time or "").strip()
    away_osi = gd.away_osi if gd.away_osi is not None else 50.0
    home_osi = gd.home_osi if gd.home_osi is not None else 50.0
    osi_total = max(away_osi + home_osi, 1.0)
    away_pct = away_osi / osi_total * 100.0
    home_pct = home_osi / osi_total * 100.0
    away_fav = " matchup-banner__team--favored" if favored == gd.away else ""
    home_fav = " matchup-banner__team--favored" if favored == gd.home else ""
    lean_cls = edge_grade(lean_margin / 100) if lean_margin >= 0.25 else "c-mid"
    compact_cls = " matchup-banner--compact" if compact else ""
    away_osi_cell = (
        f'<span class="matchup-banner__osi-tag">{val_grade_html(away_osi, "osi", digits=0, suffix=" OSI", bold=False)}</span>'
        if gd.away_osi is not None else ""
    )
    home_osi_cell = (
        f'<span class="matchup-banner__osi-tag">{val_grade_html(home_osi, "osi", digits=0, suffix=" OSI", bold=False)}</span>'
        if gd.home_osi is not None else ""
    )
    kickoff = (
        f'<div class=matchup-banner__kickoff><span>{esc(start)}</span></div>'
        if start else ""
    )
    pitchers = ""
    if not compact:
        pitchers = f"""<div class=matchup-banner__pitchers>
      <div class="matchup-banner__sp matchup-banner__sp--away">
        {_headshot(away_id)}
        <div>
          <span class=mut>Away SP</span>
          <b>{esc(gd.away_sp)}</b>
          <div class=matchup-banner__sp-stats>{_hand_pill(gd.away_hand)}{_sp_stat_chips(gd, "away")}</div>
        </div>
      </div>
      <div class=matchup-banner__vs>VS</div>
      <div class="matchup-banner__sp matchup-banner__sp--home">
        <div>
          <span class=mut>Home SP</span>
          <b>{esc(gd.home_sp)}</b>
          <div class=matchup-banner__sp-stats>{_hand_pill(gd.home_hand)}{_sp_stat_chips(gd, "home")}</div>
        </div>
        {_headshot(home_id)}
      </div>
    </div>"""
    return f"""<div class="matchup-banner{compact_cls}">
  <div class=matchup-banner__teams>
    <div class="matchup-banner__team matchup-banner__team--away{away_fav}">
      {_logo(gd.away, "tlogo lg")}
      <div class=matchup-banner__team-copy>
        <span class=matchup-banner__abbr>{esc(gd.away)}</span>{away_osi_cell}
      </div>
    </div>
    <div class=matchup-banner__center>
      <span class=matchup-banner__label>Projected score</span>
      <div class=matchup-banner__score>
        <span class=matchup-banner__runs>{prob.exp_away_runs:.1f}</span>
        <span class=matchup-banner__dash>–</span>
        <span class=matchup-banner__runs>{prob.exp_home_runs:.1f}</span>
      </div>
      <div class=matchup-banner__meta>
        {val_chip_html(prob.exp_total, "game_total", digits=1, suffix=" total")}
        <span class=mut>·</span>
        <span class=matchup-banner__lean>Lean <b class="{lean_cls}">{esc(favored)} {lean_margin:+.1f}</b></span>
      </div>
    </div>
    <div class="matchup-banner__team matchup-banner__team--home{home_fav}">
      <div class=matchup-banner__team-copy>
        <span class=matchup-banner__abbr>{esc(gd.home)}</span>{home_osi_cell}
      </div>
      {_logo(gd.home, "tlogo lg")}
    </div>
  </div>
  <div class=matchup-banner__osi-bar aria-hidden=true>
    <span class="matchup-banner__osi-seg matchup-banner__osi-seg--away" style="width:{away_pct:.1f}%"></span>
    <span class="matchup-banner__osi-seg matchup-banner__osi-seg--home" style="width:{home_pct:.1f}%"></span>
  </div>
  {pitchers}{kickoff}
</div>"""


def _matchup_kpi_strip(r: dict, esc, freshness: str) -> str:
    gd, prob = r["gd"], r["probs"]
    sim = r.get("simulation")
    total_rng = (
        f'{sim.total_p10:.0f}–{sim.total_p90:.0f}'
        if sim is not None else "—"
    )
    conf_tone = "pos" if prob.confidence == "high" else ("warnc" if prob.confidence == "medium" else "mut")
    fair_ml = fair_price(prob.p_home_win)
    return f"""<div class=matchup-kpi-strip>
  <div class=matchup-kpi><span class=k>{esc(gd.away)} win</span><span class=v>{prob_chip_html(prob.p_away_win, digits=1)}</span></div>
  <div class=matchup-kpi><span class=k>{esc(gd.home)} win</span><span class=v>{prob_chip_html(prob.p_home_win, digits=1)}</span></div>
  <div class=matchup-kpi><span class=k>Fair {esc(gd.home)} ML</span><span class=v>{fair_ml:+d}</span></div>
  <div class=matchup-kpi><span class=k>80% total</span><span class=v>{val_chip_html(prob.exp_total, "game_total", digits=1)} <span class=mut style="font-size:var(--mm-text-xs)">({total_rng})</span></span></div>
  <div class=matchup-kpi><span class=k>Confidence</span><span class=v><span class="pill {conf_tone}">{esc(prob.confidence)}</span></span></div>
  <div class=matchup-kpi><span class=k>Data age</span><span class=v>{esc(freshness)}</span></div>
</div>"""


def matchup_summary_html(report: dict) -> str:
    """Compact matchup card — optional embed; the app shell uses full ``report_body`` per game."""
    esc = html.escape
    markets = report.get("markets") or []
    mrows = ""
    for market in markets[:4]:
        edge = market.get("edge")
        mkt = esc(str(market.get("label") or market.get("market") or ""))
        edge_cell = (
            f'<b class={edge_grade((edge or 0) / 100)}>{edge:+.1f}pt</b>'
            if edge is not None else '<span class=mut>—</span>'
        )
        mrows += (
            f'<tr><td>{mkt}</td><td>{esc(str(market.get("side") or ""))}</td>'
            f'<td>{pct_chip_html(market.get("model"), digits=1)}</td><td>{edge_cell}</td></tr>'
        )
    if not mrows:
        mrows = '<tr><td class=mut colspan=4>No priced markets on this slate.</td></tr>'
    banner = _matchup_banner(report, esc, compact=True)
    return f"""<div class=matchup-summary>
 {banner}
 <div class=ca-board><div class=body>
   <div class=table-scroll><table><tr><th>Market</th><th>Side</th><th>Model%</th><th>Edge</th></tr>{mrows}</table></div>
 </div></div></div>"""


def report_body(r):
    """Render a matchup as a betting decision surface, not a written report."""
    gd, esc = r["gd"], html.escape

    def market_row(market):
        return _graded_market_row(market, esc)

    market_rows = "".join(market_row(market) for market in r["markets"])
    opportunity = max(
        (market for market in r["markets"] if market["edge"] is not None),
        key=lambda market: market["edge"],
        default=None,
    )
    if opportunity and opportunity["edge"] > 0:
        edge_cls = edge_grade((opportunity.get("edge") or 0) / 100)
        decision = (
            f'<div class="matchup-verdict vbar {opportunity["tone"]}">'
            f'<span class="pill {opportunity["tone"]} matchup-verdict__badge">{opportunity["state"]}</span>'
            f'<span class=matchup-verdict__pick><b>{esc(opportunity["label"])}</b></span>'
            f'<span class=matchup-verdict__stats>'
            f'model {pct_chip_html(opportunity.get("model"), digits=1)} '
            f'market {pct_chip_html(opportunity.get("impl"), digits=1)} '
            f'edge <b class="{edge_cls}">{opportunity["edge"]:+.1f}pt</b>'
            f'</span></div>'
        )
    else:
        reason = (
            "No positive priced edge"
            if any(market["mkt"] is not None for market in r["markets"])
            else "No paired market snapshot"
        )
        decision = f'<div class="matchup-verdict vbar mut"><span class="pill mut">NO ACTION</span><span>{esc(reason)}</span></div>'

    banner = matchup_banner_html(r, esc)
    factors = r.get("factors") or []
    repo = r.get("repo")
    if repo is None:
        repo = DataRepository(r.get("data_dir"))

    context_panel = matchup_context_html(r, gd, repo, esc)
    advantage_panel = advantage_panel_html(gd, r.get("advantage", []), esc)
    run_impacts_panel = run_impacts_html(factors, esc)
    f5_panel = f5_section_html(r, gd, repo, esc)
    pitcher_deck = pitcher_deck_html(r, gd, repo, esc)
    risk_rows = "".join(
        f'<tr><td><b>{esc(signal.label)}</b></td>'
        f'<td>{esc(signal.implication)}</td>'
        f'<td><span class="pill {"neg" if signal.severity == "high" else "warnc"}">'
        f'{esc(signal.category)}</span></td></tr>'
        for signal in r["risks"][:5]
    ) or '<tr><td class=mut colspan=3>No additional risk flags.</td></tr>'
    sharp_rows = "".join(
        f'<tr><td>{esc(signal["market_type"])}</td><td>{esc(str(signal["selection"]))}</td>'
        f'<td>{float(signal.get("divergence") or 0) * 100:+.1f}pt</td>'
        f'<td>{"STEAM" if signal.get("steam_flag") else "—"}</td></tr>'
        for signal in r["sharp"]
    ) or '<tr><td class=mut colspan=4>No sharp-money snapshot for this game.</td></tr>'

    has_price = any(market.get("mkt") is not None for market in r["markets"])
    has_sharp = bool(r["sharp"])
    market_panel = (
        f'<div class=ca-board>{section_head("Market report", icon="markets")}<div class=body><div class=table-scroll>'
        f'<table><tr><th>Bet</th><th title="best available American price">Best</th>'
        f'<th title="book\'s price with its two-sided hold removed">No-vig fair</th>'
        f'<th title="model fair price from the projection">Model fair</th>'
        f'<th>Model%</th><th title="model% minus the no-vig market%">Edge</th>'
        f'<th>EV</th><th>State</th></tr>{market_rows}</table>'
        f'</div></div></div>'
        if has_price else ''
    )
    sharp_panel = (
        f'<div class=ca-board>{section_head("Sharp market activity", icon="markets")}<div class=body><div class=table-scroll><table>'
        f'<tr><th>Market</th><th>Side</th><th>Sharp gap</th><th>Move</th></tr>{sharp_rows}</table>'
        f'</div></div></div>'
        if has_sharp else ''
    )

    return f"""{banner}
    {decision}
    {context_panel}

    <div class=decision-grid>
      {advantage_panel}
      {run_impacts_panel}
    </div>

    {f5_panel}
    {pitcher_deck}

    {market_panel}
    {sharp_panel}
    <div class=ca-board>{section_head("What can break the projection", icon="research")}<div class=body><div class=table-scroll><table>
      <tr><th>Risk</th><th>Betting implication</th><th>Type</th></tr>{risk_rows}</table>
    </div></div></div>

    <details class=model-details><summary>Model lineage</summary>
      <p>Gate: <b>{esc(r["promotion"].get("verdict", "HOLD/ABSTAIN"))}</b> · sequential run build from lineup, SP, bullpen, park, weather, ump.</p>
    </details>"""


def render_html(r):
    """Full standalone document (wraps report_body with the design-system stylesheet)."""
    e = html.escape
    script = (
        "function showReportTab(b,k){const r=b.closest('.rtabs');"
        "r.querySelectorAll('.rtabbar button').forEach(x=>x.classList.remove('on'));"
        "r.querySelectorAll('.pn').forEach(x=>x.classList.remove('on'));"
        "b.classList.add('on');r.querySelector('[data-panel=\"'+k+'\"]').classList.add('on');}"
    )
    return (f'<!DOCTYPE html><html lang=en><head><meta charset=utf-8>'
            f'<meta name=viewport content="width=device-width,initial-scale=1">'
            f'<title>{e(r["away"])}@{e(r["home"])} — MLB Model</title>'
            f'<style>{_CSS}</style></head><body><div class=wrap>{report_body(r)}</div>'
            f'<script>{script}</script></body></html>')


def main():  # pragma: no cover
    ap = argparse.ArgumentParser(description="Matchup Intelligence Report (terminal).")
    ap.add_argument("--game", required=True)
    ap.add_argument("--out", default="matchup_report.html")
    ap.add_argument("--no-fetch", action="store_true", help="use cached odds only (0 API credits)")
    args = ap.parse_args()
    away, home = (s.strip().upper() for s in args.game.split("@", 1))
    r = build_report(away, home, fetch=not args.no_fetch)
    open(args.out, "w", encoding="utf-8").write(render_html(r))
    print(f"wrote {args.out}  ({r['away']}@{r['home']})")


if __name__ == "__main__":
    main()
